#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dbuildtype=release \
    -Ddefault_library=both \
    -Dx11_backend=false \
    -Dwayland_backend=true \
    -Dxinerama=no \
    -Dcolord=no \
    -Dintrospection=false \
    -Ddemos=false \
    -Dexamples=false \
    -Dtests=false \
    -Dbuiltin_immodules=no \
    . build

ninja -C build
ninja -C build install

# We don't compile with librsvg which leads to this
# utility solely causing compiler errors for some
# packages. It has no use at all.
rm -f "$1/usr/bin/gtk-encode-symbolic-svg"

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/gtk+3.license"
