#!/bin/sh -e

make
make DESTDIR="$1" PREFIX=/usr install

mkdir -p          "$1/usr/share/paleta"
cp    -r palettes "$1/usr/share/paleta/palettes"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/paleta.license"
