#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -i \
    -e "/^CFLAGS/s/=/= $CFLAGS -static/" \
    -e "/^LDFLAGS/s/=/= $LDFLAGS -static/" \
    config.mk

make ubase-box
make DESTDIR="$1" PREFIX=/usr ubase-box-install

# Unlink things we'd rather use toybox for
unlink "$1/usr/bin/blkdiscard"
unlink "$1/usr/bin/chvt"
unlink "$1/usr/bin/clear"
unlink "$1/usr/bin/dd"
unlink "$1/usr/bin/df"
unlink "$1/usr/bin/dmesg"
unlink "$1/usr/bin/eject"
unlink "$1/usr/bin/fallocate"
unlink "$1/usr/bin/free"
unlink "$1/usr/bin/freeramdisk"
unlink "$1/usr/bin/fsfreeze"
unlink "$1/usr/bin/getty"
unlink "$1/usr/bin/hwclock"
unlink "$1/usr/bin/id"
unlink "$1/usr/bin/insmod"
unlink "$1/usr/bin/killall5"
unlink "$1/usr/bin/last"
unlink "$1/usr/bin/login"
unlink "$1/usr/bin/lsmod"
unlink "$1/usr/bin/lsusb"
unlink "$1/usr/bin/mesg"
unlink "$1/usr/bin/mknod"
unlink "$1/usr/bin/mkswap"
unlink "$1/usr/bin/mount"
unlink "$1/usr/bin/mountpoint"
unlink "$1/usr/bin/nologin"
unlink "$1/usr/bin/passwd"
unlink "$1/usr/bin/pidof"
unlink "$1/usr/bin/pivot_root"
unlink "$1/usr/bin/ps"
unlink "$1/usr/bin/pwdx"
unlink "$1/usr/bin/readahead"
unlink "$1/usr/bin/respawn"
unlink "$1/usr/bin/rmmod"
unlink "$1/usr/bin/stat"
unlink "$1/usr/bin/su"
unlink "$1/usr/bin/swapoff"
unlink "$1/usr/bin/swapon"
unlink "$1/usr/bin/switch_root"
unlink "$1/usr/bin/sysctl"
unlink "$1/usr/bin/truncate"
unlink "$1/usr/bin/umount"
unlink "$1/usr/bin/unshare"
unlink "$1/usr/bin/uptime"
unlink "$1/usr/bin/watch"
unlink "$1/usr/bin/who"
