#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -i \
    -e "/^CFLAGS/s/=/= $CFLAGS -static/" \
    -e "/^LDFLAGS/s/=/= $LDFLAGS -static/" \
    config.mk

make ubase-box
make DESTDIR="$1" PREFIX=/usr ubase-box-install

# Unlink overlaps, su doesn't support -c
for bin in blkdiscard chvt clear dd df dmesg eject   \
           fallocate free freeramdisk fsfreeze halt  \
           hwclock id insmod killall5 last login     \
           lsmod lsusb mknod mkswap mount mountpoint \
           passwd pidof pivot_root ps pwdx readahead \
           respawn rmmod stat swapoff swapon         \
           switch_root su sysctl truncate unshare    \
           umount uptime watch who
do
    unlink "$1/usr/bin/$bin"
done

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/ubase.license"
