#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -i \
    -e "/^CFLAGS/s/=/= $CFLAGS -static/" \
    -e "/^LDFLAGS/s/=/= $LDFLAGS -static/" \
    config.mk

make ubase-box
make DESTDIR="$1" PREFIX=/usr ubase-box-install

# Unlink overlaps, su doesn't support -c
for bin in clear dd getty id mknod respawn su stat truncate; do
    unlink "$1/usr/bin/$bin"
done

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/ubase.license"
