#!/bin/sh -e

patch -p1 < remove-po-tests.patch

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin

# Because we patch out po/man-po/testsuite, we have to edit
# the generated Makefile. Because the Makefile is *generated*, we can't
# simply patch it. 

sed -i '/ACLOCAL_M4/d'   Makefile
sed -i '/ACLOCAL/d'      Makefile
sed -i '/m4/d'           Makefile
sed -i '/configure.ac/d' Makefile

gmake
gmake DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/procps-ng.license"
