#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --without-x \
    --disable-Werror \
    --enable-user-session \
    --with-console-auth-dor=/run/console \
    --with-system-pid-file=/run/dbus/pid \
    --with-system-socket=/run/dbus/system_bus_socket

gmake
gmake DESTDIR="$1" install

# Useless on UNIX, only nontest file that isn't AFL
rm -f "$1/usr/bin/dbus-cleanup-sockets"

# Install service
install -Dm755 dbus.run "$1/etc/sysmgr/dbus"

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/dbus.license"
