#!/bin/sh -e

./configure \
    --prefix=/usr \
    --datadir=/usr/share/openssh \
    --sysconfdir=/etc/ssh \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib/openssh \
    --without-selinux \
    --with-privsep-user=nobody \
    --with-mantype=doc \
    --without-rpath \
    --disable-strip \
    --with-ssl-engine \
    --with-pid-dir=/run \
    --disable-wtmp \
    --disable-utmp

make
make DESTDIR="$1" install

# Install service, utility
install -Dm755 sshd.run           "$1/etc/sysmgr/sshd"
install -m755 contrib/ssh-copy-id "$1/usr/bin/ssh-copy-id"

# Install the license
install -Dm755 LICENCE "$1/usr/share/LICENSES/openssh.license"
