#!/bin/sh -e

echo "## STILL IN TESTING ##" 
sleep 10

cargo build --release
cargo install --root="$1/usr"

"$1/usr/bin/uutils" --help | tail -n 74 | while read -r util; do
    ln -sv uutils "$1/usr/bin/$util"
done

# uutils cp is not fully implemented and fails to work with kiss a
unlink "$1/usr/bin/cp"
