#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-nls \
    ac_cv_path_DOXYGEN=false

make
make DESTDIR="$1" install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/libexif.license"
