#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < static.patch

meson \
    --prefix=/usr \
    -Ddefault_library=static \
    -Dbuildtype=release \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-x11=false \
    -Dxkb-config-root=/usr/share/X11/xkb \
    -Dx-locale-root=/usr/share/X11/locale \
    -Denable-xkbregistry=false \
    . build

ninja -C build
ninja -C build install
