#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --buildtype=release \
    -Ddefault_library=both \
    -Denable-x11=false \
    -Denable-docs=false \
    -Denable-wayland=true \
    -Denable-xkbregistry=false \
    -Dxkb-config-root=/usr/share/X11/xkb \
    -Dx-locale-root=/usr/share/X11/locale \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/libxkbcommon.license"
