#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/glib-2.0', /glib-2.0', static: true/"       meson.build
sed -i "s/gobject-2.0', /gobject-2.0', static: true/" meson.build
sed -i "s/export-2.0', /export-2.0', static: true/"   meson.build
sed -i "s/gio-2.0', /gio-2.0', static: true/"         meson.build
sed -i "s/libpng', /libpng', static: true/"           meson.build
sed -i "s/zlib', /zlib', static: true/"               meson.build
sed -i "/subdir('tests')/d"                           meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dbuildtype=release \
    -Dbuiltin_loaders=all \
    -Ddefault_library=static \
    -Dpng=true \
    -Dgir=false \
    -Dman=false \
    -Dx11=false \
    -Ddocs=false \
    -Djasper=false \
    -Dgio_sniffing=false \
    -Dinstalled_tests=false \
    . build

ninja -C build
ninja -C build install
