#!/bin/sh -e

export DESTDIR="$1"

sed -i "/subdir('tests')/d" meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dbuildtype=release \
    -Dbuiltin_loaders=all \
    -Ddefault_library=static \
    -Dpng=true \
    -Dgir=false \
    -Dman=false \
    -Dx11=false \
    -Ddocs=false \
    -Djasper=false \
    -Dgio_sniffing=false \
    -Dinstalled_tests=false \
    . build

ninja -C build
ninja -C build install
