#!/bin/sh -e 

# Include blis library for blas
# -D__MUSL__ required for packages like Rcpp
export CFLAGS="-I/usr/include/blis -fopenmp $CFLAGS"
export CXXFLAGS="-I/usr/include/blis -fopenmp $CXXFLAGS -D__MUSL__"
export FFLAGS="-I/usr/include/blis -fopenmp $FFLAGS"
export FCFLAGS="-I/usr/include/blis -fopenmp $FCFLAGS"

./configure \
    --prefix=/usr \
    --enable-memory-profiling \
    --enable-R-shlib \
    --with-blas="/usr/lib/libblis.so /usr/lib/libblis.so.3" \
    --with-lapack

make
make DESTDIR="$1" install
