#!/bin/sh -e

# Make sbase tar accept arguments without dash
patch -p1 < tar-dash-remove.patch

make LDFLAGS="$LDFLAGS -static" sbase-box
make DESTDIR="$1" PREFIX=/usr   sbase-box-install

# Unlink sed, because '-i' is widey used
unlink "$1/usr/bin/sed"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/sbase.license"
