#!/bin/sh -e

patch -p1 < fix-busybox-diff.patch

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --cpu=X86 \
    --as=nasm \
    --enable-vp8 \
    --enable-vp9 \
    --enable-shared \
    --enable-experimental \
    --enable-runtime-cpu-detect \
    --enable-postproc \
    --disable-docs \
    --disable-tools \
    --disable-examples \
    --disable-install-docs \
    --disable-install-srcs \
    --disable-install-bins

gmake
gmake DESTDIR="$1" install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/libvpx.license"
