#!/bin/sh -e

export DESTDIR="$1"

cmake -B zbuild \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DZSTD_BUILD_SHARED=OFF \
    -DZSTD_USE_STATIC_RUNTIME=ON \
    -G Ninja build/cmake

ninja -C zbuild
ninja -C zbuild install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/zstd.license"
