#!/bin/sh -e

mkdir bin
ln -s /usr/bin/gmake bin/make
export PATH=$PWD/bin:$PATH

export CARGO_HOME=$PWD

(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        # Strip the filename from the sha256sum output.
        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
    done
)

mkdir -p .cargo

cat > .cargo/config.toml << EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

cargo build \
    --frozen \
    --release

install -Dm755 target/release/gitui "$1/usr/bin/gitui"

# Install the license
install -Dm755 LICENSE.md "$1/usr/share/LICENSES/gitui.license"
