#!/bin/sh -e

export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib \
    --disable-nls \
    LIBS="-lssl -lcrypto -lzstd -lz"

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/gnupg1.license"
