#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dbuildtype=release \
    . build

ninja -C build
ninja -C build install

install -Dm755 LICENSE "$1/usr/share/LICENSES/tllist.license"
