#!/bin/sh -e

./configure \
    --prefix=/usr \
    --without-tests \
    --without-examples

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/expat.license"
