#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-cpio \
    --disable-bsdcat \
    --without-xml2 \
    --without-expat \
    --without-nettle \
    --without-openssl

make
make DESTDIR="$1" install

ln -s bsdtar  "$1/usr/bin/tar"

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libarchive.license"
