#!/bin/sh -e

./configure \
    --build=x86_64-linux-musl \
    --host=x86_64-linux-musl \
    --prefix=/usr \
    --enable-nasm \
    --enable-expopt=full \
    --disable-gtktest \
    --disable-shared

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install
