#!/bin/sh -e

sed -i 's/\(curl_LDADD =\)/\1 -all-static/' src/Makefile.in

./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-optimize \
    --enable-unix-sockets \
    --enable-hidden-symbols \
    --disable-ares \
    --disable-ldap \
    --disable-debug \
    --disable-manual \
    --without-icu \
    --without-libpsl \
    --without-libidn \
    --without-libidn2 \
    --without-librtmp \
    --with-pic \
    --with-openssl \
    --with-ca-fallback

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/curl.license"
