#!/bin/sh -e

# Upstream broke static linking. It is still supported via LDFLAGS but this
# disables output of the shared library. This sed call adds -all-static to the
# curl commands' compilation (keeping libraries in tact).
# See: https://github.com/curl/curl/issues/7475
sed 's/\(curl_LDADD =\)/\1 -all-static/' src/Makefile.in > _
mv -f _ src/Makefile.in

patch -p1 < fix-http-dec-flag.patch

./configure \
    ac_cv_path_PERL=true \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-optimize \
    --enable-unix-sockets \
    --enable-symbol-hiding \
    --disable-ares \
    --disable-ldap \
    --disable-docs \
    --disable-manual \
    --disable-debug \
    --with-ca-fallback \
    --with-openssl \
    --with-pic \
    --without-librtmp \
    --without-libpsl \
    --without-libidn2 \
    --without-brotli

make
make DESTDIR="$1" install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/curl.license"
