#!/bin/sh -e

build_zstd() (

    HAVE_ZLIB=1
    HAVE_LZMA=1
    HAVE_THREAD=1

    cd programs

    export CFLAGS="$CFLAGS -static -pthread"
    export LDFLAGS="$LDFLAGS -static"

    gmake CC=clang zstd-pgo
    gmake PREFIX=/usr DESTDIR="$1" install
)

build_libzstd() (

    cd lib

    export CFLAGS="$CFLAGS -flto -ffat-lto-objects -fuse-linker-plugin \
                           -ffunction-sections -fdata-sections \
                           -fmerge-all-constants \
                           -Wl,--gc-sections -Wl,-z,norelro \
                           -Wno-unused-command-line-argument \
                           -Wno-ignored-optimization-argument"

    gmake PREFIX=/usr lib-mt
    gmake PREFIX=/usr DESTDIR="$1" install
)

build_zstd "$1"
build_libzstd "$1"

# Symlink for all the things we built in
for bin in gzip lzma xz zcat ungz unlzma unxz; do
    ln -s zstd "$1/usr/bin/$bin"
done

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/zstd.license"
