#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
sed -i "/subdir('tests')/d" meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddefault_library=static \
    -Ddocs=false \
    -Dintrospection=false \
    . build

ninja -C build
ninja -C build install
