#!/bin/sh -e

: > tests/meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddocs=false \
    -Dintrospection=false \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/atk.license"
