#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-static \
    --with-shadow \
    --with-timestamp \
    --without-pam

make
make DESTDIR="$1" install

install -Dm600 doas.conf "$1/etc/doas.conf"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/opendoas.license"
