#!/bin/sh -e

export CARGO_HOME="$PWD"

(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        # Strip the filename form the sha256sum output
        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
        done
)

mkdir -p .cargo

cat > .cargo/config << EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

cargo build \
    --offline \
    --release

install -Dm755 target/release/wl-clip  "$1/usr/bin/wl-clip"
install -Dm755 target/release/wl-copy  "$1/usr/bin/wl-copy"
install -Dm755 target/release/wl-paste "$1/usr/bin/wl-paste"

# Install the license
install -Dm755 LICENSE-MIT "$1/usr/share/LICENSES/wl-clipboard-rs.license"
