#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -i '/#if defined(LINUX)/a #include <net/if.h>' \
dom/media/webrtc/transport/third_party/nICEr/src/stun/addrs-netlink.c

# autoconf requires GNU m4.
(
    cd m4-1.4.18
    ./configure \
        --prefix="$PWD/../junk"

    make
    make install
)

export PATH=$PWD/junk/bin:$PATH

# Build autoconf 2.13 for Firefox's sole use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

# Build yasm for Firefox's sole use.
# Firefox is the only package which needs it
# and upstream is kinda dead.
(
    cd yasm

    ./configure \
        --prefix="$PWD/../junk"

    make
    make install
)

mkdir -p build && cd build

# Override ccache.
export CC="${CC:-/usr/bin/cc}"
export CXX="${CXX:-/usr/bin/c++}"

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/firefox"
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0"
export MOZ_DEBUG_FLAGS=-g0
export MOZ_NOSPAM=1
export CXXSTDLIB=c++
export SHELL=/bin/sh
export BUILD_OFFICIAL=1
export MOZILLA_OFFICIAL=1
export USE_SHORT_LIBNAME=1
export MACH_USE_SYSTEM_PYTHON=1

    ../mach configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --with-system-ffi \
    --with-system-png \
    --with-system-jpeg \
    --with-system-zlib \
    --with-system-pixman \
    --without-system-nss \
    --without-system-nspr \
    --without-system-libvpx \
    --disable-eme \
    --disable-dbus \
    --disable-gold \
    --disable-tests \
    --disable-vtune \
    --disable-webrtc \
    --disable-updater \
    --disable-elf-hack \
    --disable-jemalloc \
    --disable-profiling \
    --disable-necko-wifi \
    --disable-callgrind \
    --disable-pulseaudio \
    --disable-crashreporter \
    --disable-accessibility \
    --disable-debug-symbols \
    --disable-parental-controls \
    --disable-system-extension-dirs \
    --enable-alsa \
    --enable-strip \
    --enable-release \
    --enable-rust-simd \
    --enable-linker=lld \
    --enable-install-strip \
    --enable-official-branding \
    --enable-application=browser \
    --enable-optimize="$CFLAGS -w" \
    --enable-default-toolkit=cairo-gtk3-wayland

../mach build
DESTDIR="$1" ../mach install

# Remove a lot of unneeded "stuff".
rm -rf "$1/usr/include"
rm -rf "$1/usr/lib/firefox-devel"
rm -rf "$1/usr/share/idl"
rm -rf "$1/usr/lib/firefox/gtk2"
rm -f  "$1/usr/lib/firefox/browser/features/fxmonitor@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/screenshots@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/webcompat-reporter@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi"
rm -f  "$1/usr/lib/firefox/browser/features/doh-rollout@mozilla.org.xpi"

# Install the license
install -Dm755 license.html "$1/usr/share/LICENSES/firefox.license"
