#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --enable-static-libc

gmake
gmake DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/s6.license" 
