#!/bin/sh -e

patch -p1 < libpng-1.6.37-apng.patch

./configure \
    --prefix=/usr \
    --enable-hardware-optimizations

make
make DESTDIR="$1" install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/libpng.license"
