#!/bin/sh -e

patch -p1 < libpng-1.6.37-apng.patch

./configure \
    --prefix=/usr \
    --disable-shared \
    --enable-hardware-optimizations

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install
