#!/bin/sh -e

sed -i 's/ctors/init_array/' blake3_cpuid.S

export CFLAGS="$CFLAGS -DNDEBUG"

make PREFIX=/usr
make PREFIX=/usr DESTDIR="$1" install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/b3sum.license"
