#!/bin/sh -e

export DESTDIR="$1"

# Remove 'libelf' dependency.
sed -i 's/HAVE_LIBELF/HAVE_KISS/' gio/meson.build

# Remove 'util-linux' dependency.
sed -i 's/libmount_dep.found()/false/' meson.build

: > glib/tests/meson.build
: > tests/meson.build
: > gobject/tests/mesom.build
: > gio/tests/meson.build
: > fuzzing/meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dbuildtype=release \
    -Dman=false \
    -Dfam=false \
    -Dnls=disabled \
    -Dglib_assert=false \
    -Dglib_checks=false \
    -Dlibmount=disabled \
    -Dglib_debug=disabled \
    -Dinstalled_tests=false \
    . build

ninja -C build
ninja -C build install

#Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/glib.license"
