#!/bin/sh -e

cat << EOF
I don't know what more you expected from me!

Congratulations, you're lazy. 

Make sure you tweak /etc/fstab to suit your drives. It's not fatal if it's
inaccurate. 

Also check that the /etc/*.new files are moved over!
EOF
