#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-rpath \
    --disable-doxygen-docs \
    --disable-xmms-plugin \
    --disable-thorough-tests \
    --with-pic

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING.Xiph "$1/usr/share/LICENSES/flac.license"
