#!/bin/sh -e

# Perhaps we try clang on for size
rm -f .clang

# Patches
for patch in *.patch; do
    patch -p1 < $patch
done

# Set the kernel up for success!
scripts/setlocalversion --save-scmversion
cp config .config
make HOSTCC=clang CC=clang olddefconfig
make HOSTCC=clang CC=clang kernelrelease > version

# Useful variables
kernver="$(cat version)"
modulesdir="$1/usr/lib/modules/$kernver"
builddir="$modulesdir/build"

# Make that bad boy!
echo "Making linux-"$kernver""
make HOSTCC=clang CC=clang

echo "Installing modules..."
make HOSTCC=clang CC=clang INSTALL_MOD_PATH="$1/usr" modules_install

echo "Cleaning up..."
rm "$modulesdir/build" "$modulesdir/source"

chmod -Rc u=rwX,go=rX "$1"

echo "Copying files to build external modules..."
install -Dt "$builddir"                 -m644 .config Makefile Module.symvers System.map version vmlinux
install -Dt "$builddir/arch/x86"        -m644 arch/x86/Makefile
install -Dt "$builddir/arch/x86/kernel" -m644 arch/x86/kernel/asm-offsets.s
install -Dt "$builddir/kernel"          -m644 kernel/Makefile
install -Dt "$builddir/drivers/md"      -m644 drivers/md/*.h
install -Dt "$builddir/net/mac80211"    -m644 net/mac80211/*.h
install -Dt "$builddir/tools/objtool"         tools/objtool/objtool

cp -a scripts          "$builddir/scripts"
cp -a include          "$builddir/include"
cp -a arch/x86/include "$builddir/arch/x86/include"

find . -name "Kconfig*" -exec install -Dm644 {} "$builddir/{}" \;

echo "Removing cruft..."
rm -r "$builddir/Documentation"
find -L "$builddir" -type l -delete
find "$builddir" -type f -name "*.o" -delete

echo "Laying trap..."
mkdir -p "$1/usr/src"
ln -sv "$builddir" "$1/usr/src/linux"

echo "Installing kernel..."
mkdir -p "$1/boot"
make INSTALL_PATH="$1/boot" install
