#!/bin/sh -e

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-tests

make
make DESTDIR="$1" install

install -Dm755 update-certdata.sh "$1/etc/ssl"

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/libressl.license"
