#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --rundir=/run \
    --libexecdir=/usr/lib/dhcpcd \
    --without-udev

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" install

# Install runit service.
install -Dm 755 dhcpcd.run "$1/etc/sv/dhcpcd/run"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/dhcpcd.license"
