#!/bin/sh -e

export DESTDIR="$1"

# Remove bash dependency
sed -i 's/bash/sh/g' Makefile

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --libexecdir=/usr/lib \
    --sysconfdir=/etc \
    --disable-gtk \
    --disable-docs \
    --disable-user \
    --disable-debug-info \
    --disable-linux-user \
    --enable-sdl \
    --enable-kvm \
    --enable-curses \
    --enable-system

ninja -C build
ninja -C build install

rm -rf build

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --libexecdir=/usr/lib \
    --sysconfdir=/etc \
    --disable-gtk \
    --disable-docs \
    --disable-user \
    --disable-system \
    --disable-debug-info \
    --enable-sdl \
    --enable-kvm \
    --enable-curses \
    --enable-linux-user \
    --static

ninja -C build
ninja -C build install

# Install some files for RISCV emulation
install -Dm644 uboot.elf \
    "$1/usr/lib/u-boot/qemu-riscv64_smode/uboot.elf"
install -Dm644 fw_jump.elf \
    "$1/usr/lib/riscv64-linux-gnu/opensbi/generic/fw_jump.elf"

# Install the license
install -Dm755 COPYING         "$1/usr/share/LICENSES/qemu.license"
install -Dm755 COPYING.LIB     "$1/usr/share/LICENSES/qemu-lib.license"
install -Dm755 opensbi.license "$1/usr/share/LICENSES/opensbi.license"
