#!/bin/sh -e

patch -p1 < wlroots_0.11.0.patch

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=plain \
    -Duse_system_wlroots=enabled \
    -Duse_system_wfconfig=enabled \
    . build

ninja -C build
ninja -C build install

install -Dm644 wayfire.ini "$1/usr/share/wayfire/wayfire.ini.default"
