#!/bin/sh -e

# Set the kernel up for success!
scripts/setlocalversion --save-scmversion
cp config .config

make \
    olddefconfig \
    CC=clang \
    HOSTCC=clang

make \
    headers \
    CC=clang \
    HOSTCC=clang

# rsync is required for headers_install.
# So we'll install them ourself. 

find usr/include -name \*.h -type f | while read -r file; do
    install -Dm644 "$file" "$1/$file" 
done
