#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DFLANG_INCLUDE_DOCS=OFF \
    -DFLANG_INCLUDE_TESTS=OFF \
    -Wno-dev -G Ninja flang

cmake --build   build
cmake --install build
