#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var

make
make DESTDIR="$1" install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/libgcrypt.license"
