#!/bin/sh -e

cat >> different-orphans.patch << EOF
--- a/contrib/kiss-orphans
+++ b/contrib/kiss-orphans
@@ -7,8 +7,8 @@
     case $pkg in
         # Exemptions for orphans which aren't really
         # orphans. Exclude them from the list.
-        baseinit|baselayout|gcc|e2fsprogs|musl|\\
-        make|busybox|bzip2|grub|kiss|git)
+        baseinit|baselayout|bzip2|dash|kiss|libarchive|\\
+        make|musl|nawk|openntpd|toybox|uutils|zstd)
             continue
     esac
 
EOF

patch -p1 < different-orphans.patch

mkdir -p "$1/usr/bin"

# Install kiss utilities.
cp -f kiss contrib/* "$1/usr/bin/"

# Install distribution documentation.
for doc in docs/site/*.txt; do
    install -Dm644 "$doc" "$1/usr/share/doc/kiss/${doc##*/}"
done

# Install the Wiki.
cp -r wiki "$1/usr/share/doc/kiss/wiki"

# Remove unnecessary pages.
rm -f "$1/usr/share/doc/kiss/wiki/README.txt" \
      "$1/usr/share/doc/kiss/news.txt" \
      "$1/usr/share/doc/kiss/blog.txt" \
      "$1/usr/share/doc/kiss/screenshots.txt"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/kiss.license"
