#!/bin/sh -e

# Tests for clang are failing, for some reason?
export CFLAGS="$CFLAGS -fno-builtin"
export CXXFLAGS="$CXXFLAGS -fno-builtin"

./configure \
    --prefix=/usr \
    --disable-nls \
    --without-libtextstyle-prefix

make
make DESTDIR="$1" install
