#!/bin/sh -e

./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --mandir=/usr/share/man \
    --enable-sh \
    --enable-ksh \
    --enable-lto \
    --enable-static

make
make DESTDIR="$1" install

# Install the license
install -Dm644 LEGAL "$1/usr/share/LICENSES/oksh.license"
