#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dx11=disabled \
    -Dtls=disabled \
    -Dglx=disabled \
    -Degl=true \
    -Dgles1=true \
    -Dgles2=true \
     . build

ninja -C build
ninja -C build install
