#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/ \
    -Ddefault_library=static \
    -Dbuildtype=release \
    inih inih/build

ninja -C inih/build
DESTDIR="$PWD" ninja -C inih/build install

export CFLAGS="$CFLAGS -I$PWD/include"
export LDFLAGS="$LDFLAGS -L$PWD/lib"
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:$PWD/lib/pkgconfig"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dbuildtype=release \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/xdg-desktop-portal-wlr.license"
