#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"
export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1"

sed -i 's/ -ltinfo//g' configure

./configure \
    --prefix=/usr \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5 \
    --disable-shared

make
make DESTDIR="$1" install

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/sqlite.license"
