#!/bin/sh -e

(
    cd gperf

    ./configure \
        --prefix=/usr

    make -B
    make -B DESTDIR="$PWD/../garbo" install
)

export PATH="$PWD/garbo/usr/bin:$PATH"

export DESTDIR="$1"

meson \
    --prefix=/usr \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 LICENSE.LGPL2.1 "$1/usr/share/LICENSES/basu.license"
