#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-fsck \
    --enable-libuuid \
    --enable-libblkid \
    --enable-static-programs \
    --disable-more \
    --disable-rpath \
    --disable-assert \
    --disable-shared \
    --disable-makeinstall-chown \
    --without-udev \
    --without-python \
    --without-systemd

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install

# Fix broken --sbindir.
mv -f "$1/usr/sbin/"* "$1/usr/bin"
rmdir "$1/usr/sbin"
