#!/bin/sh -e

export CPPFLAGS="$CPPFLAGS -DSQLITE_ENABLE_COLUMN_METADATA=1"

export CFLAGS="$CFLAGS -fPIC"

sed -i 's/ -ltinfo//g' configure

./configure \
    --prefix=/usr \
    --enable-threadsafe \
    --enable-dynamic-extensions \
    --enable-fts5 \
    --disable-shared

make
make DESTDIR="$1" install
