#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

ln -sf pkgconf "$1/usr/bin/pkg-config"

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/pkgconf.license"
