#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dbuildtype=release \
    -Ddocumentation=false \
    -Ddtd_validation=false \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/wayland.license"
