#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/expat', /expat', static: true /" meson.build
sed -i "s/ffi', /ffi', static: true, /"    meson.build
sed -i "s/subdir('tests')//"               meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dbuildtype=release \
    -Ddtd_validation=false \
    -Ddocumentation=false \
    . build

ninja -C build
ninja -C build install
