#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -i 's/cairo.h/cairo\/cairo.h/' \
    plugins/common/wayfire/plugins/common/cairo-util.hpp
sed -i 's/cairo.h/cairo\/cairo.h/' \
    plugins/decor/deco-button.hpp
sed -i 's/cairo.h/cairo\/cairo.h/' \
    plugins/decor/deco-subsurface.cpp

meson \
    --prefix=/usr \
    --buildtype=release \
    -Dexamples=false \
    -Dprint_trace=false \
    -Dxwayland=disabled \
    -Dxcb-error=disabled \
    -Dx11-backend=disabled \
    . build

ninja -C build
ninja -C build install

install -Dm 644 wayfire.ini "$1/etc/wayfire/wayfire.ini"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/wayfire.license"
