#!/bin/sh -e

export DESTDIR="$1"

(
    cd evdev
    export DESTDIR="$OLDPWD"

    meson \
        --prefix=/usr \
        --buildtype=release \
        -Ddefault_library=static \
        -Ddocumentation=disabled \
        -Dtests=disabled \
        . build

    ninja -C build
    ninja -C build install
)

# We need some headers from glm
cp -r glm/glm "usr/include/glm"

cat >> usr/lib/pkgconfig/glm.pc << EOF
prefix=/usr
includedir=\${prefix}/include

Name: GLM
Description: OpenGL Mathematics
Version: 0.9.9.8
Cflags: -I\${includedir}
EOF

#include our glm C++ bindings

#export PKG_CONFIG_PATH="$PWD/usr/lib/pkgconfig"
export CFLAGS="$CFLAGS -I$PWD/usr/include -I$PWD/usr/include/libevdev-1.0"
export CXXFLAGS="$CXXFLAGS -I$PWD/usr/include -I$PWD/usr/include/libevdev-1.0"
export LDFLAGS="$LDFLAGS -L$PWD/usr/lib"

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Cairo is installed... elsewhere...
sed -i 's/cairo.h/cairo\/cairo.h/' \
    plugins/common/wayfire/plugins/common/cairo-util.hpp
sed -i 's/cairo.h/cairo\/cairo.h/' \
    plugins/decor/deco-button.hpp
sed -i 's/cairo.h/cairo\/cairo.h/' \
    plugins/decor/deco-subsurface.cpp

sed -i "/subdir('test')/d" \
    subprojects/wf-config/meson.build
sed -i "s/libevdev'/libevdev', static: true/" \
    subprojects/wf-config/meson.build
sed -i "s/libxml-2.0'/libxml-2.0', static: true/" \
    subprojects/wf-config/meson.build

meson \
    --prefix=/usr \
    --buildtype=release \
    -Ddefault_library=static \
    -Dpkg_config_path="$PWD/usr/lib/pkgconfig" \
    -Dprint_trace=false \
    -Dxwayland=disabled \
    -Duse_system_wlroots=enabled \
    -Duse_system_wfconfig=disabled \
    . build

ninja -C build
ninja -C build install

install -Dm 644 wayfire.ini "$1/etc/wayfire/wayfire.ini"

# Include the plugins.
(
    cd pl

    export CFLAGS="$CFLAGS -I$1/usr/include"
    export CXXFLAGS="$CXXFLAGS -I$1/usr/include"
    export LDFLAGS="$LDFLAGS -L$1/usr/lib"

    meson \
        --prefix=/usr \
        --buildtype=release \
        -Ddefault_library=static \
        -Dpkg_config_path="$OLDPWD/usr/lib/pkgconfig:$1/usr/lib/pkgconfig" \
        . build

    ninja -C build
    ninja -C build install
)

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/wayfire.license"
