#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/subdir('test')//" meson.build

meson \
    --prefix=/usr \
    --buildtype=release \
    -Ddefault_library=both \
    -Dgtk=disabled \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/pixman.license"
