#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/subdir('test')//" meson.build

meson \
    --prefix=/usr \
    -Dbuildtype=release \
    -Ddefault_library=both \
    -Dgtk=disabled \
    . build

ninja -C build
ninja -C build install
