#!/bin/sh -e

cat << EOF
In order to use the wayland backend, you will probably need to launch chromium
with:
--enabe-features=UseOzonePlatform --ozone-platform=wayland

If you have video playback issues (no video, but you have audio), you may need:
--disable-gpu-memory-buffer-video-frames

If you don't have namespaces, you will need:
--no-sandbox

I just put all of these in a script I launch chromium with.
EOF
