#!/bin/sh -e

patch -p1 < portability.patch

./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

gmake
gmake DESTDIR="$1" install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/x264.license"
