#!/bin/sh -e

patch -p1 < x264-no-bash.patch

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --enable-lto \
    --enable-pic \
    --enable-strip \
    --enable-shared \
    --enable-static \
    --disable-swscale

gmake
gmake DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/x264.license"
