#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    -Dexamples=false \
    -Dlogind=disabled \
    -Dxcb-errors=disabled \
    -Dxcb-icccm=disabled \
    -Dxwayland=disabled \
    -Dx11-backend=disabled \
    . build

ninja -C build
ninja -C build install
