#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    -Dexamples=false \
    -Dxwayland=disabled \
    -Dxcb-errors=disabled \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/wlroots.license"
