#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --prefix=/usr

gmake DESTDIR="$1" install

ln -s /usr/bin/dash "$1/usr/bin/sh"

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/dash.license"
