#!/bin/sh -e

export GOPATH="$PWD/go"
export GO111MODULE=on

cd gopls

go build \
    -modcacherw \
    -trimpath \
    -o gopls

install -Dm755 gopls "$1/usr/bin/gopls"

# Install the license
install -Dm644 ../LICENSE "$1/usr/share/LICENSES/gopls.license"
