#!/bin/sh -e

export CARGO_HOME=$PWD

(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        # Strip the filename from the sha256sum output.
        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
    done
)

mkdir -p .cargo

cat > .cargo/config << EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

# We have to explicitly exclude certain features that relate to utmp/wtmp; see
# https://wiki.musl-libc.org/faq.html#Q:-Why-is-the-utmp/wtmp-functionality-only-implemented-as-stubs?

cargo build \
    --frozen \
    --release \
    --features "$(cat feat-list)" \
    --no-default-features

install -Dm755 target/release/coreutils "$1/usr/bin/coreutils"

# We'll go ahead and add our symlinks because we created a monolithic binary
while read util; do
    ln -s coreutils "$1/usr/bin/$util"
done < feat-list

# These functions were replaced by hashsum, but we should symlink just in case
for bin in md5 sha1 sha224 sha256 sha384 sha512; do
    ln -s coreutils "$1/usr/bin/${bin}sum"
done

# Unlink ls because -t is broken. Use an alias for everything else
unlink "$1/usr/bin/ls"
# tr is also broken, somehow??
unlink "$1/usr/bin/tr"
