#!/bin/sh -e

patch -p1 < scan_all.patch
patch -p1 < usb_nodes.patch

# Missing include
sed -i '/<libgen.h>/a #include <sys/sysmacros.h>' smdev.c

make LDFLAGS="$LDFLAGS -static"
make PREFIX=/usr DESTDIR="$1" install

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/smdev.license"
