#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < build-fix.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_TESTING=OFF \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm755 LICENSE.md "$1/usr/share/LICENSES/rnp.license"
