#!/bin/sh -e

export DESTDIR="$1"

sed -i 's/llen = 76/llen = 64/' src/librepgp/stream-armor.cpp

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm755 LICENSE.md "$1/usr/share/LICENSES/rnp.license"
