#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --enable-static-libc

gmake
gmake DESTDIR="$1" install

# Install some good starting services
# Along with some example scripts
mkdir -p "$1/etc/s6-rc"
tar xf s6-rc-scripts.tar.xz?no-extract -C "$1/etc/s6-rc"

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/s6-rc.license"
