#!/bin/sh -e

export GOPATH="$PWD/go"
export GO111MODULE=on

go build \
    -modcacherw \
    -trimpath \
    ./cmd/gh

install -Dm755 gh "$1/usr/bin/gh"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/github-cli.license"
