#!/bin/sh -e

# This package mimics the download process of rust's 'x.py'
# bootstrap library to allow for the removal of the internet
# connection requirement per build.
# The bootstrap uses a custom-made rust lib, tailored specifically for
# Wyverkiss.
{
    cache_dir=build/cache/2020-11-19
    mkdir -p "$cache_dir"

    for tarball in *.tar.xz\?no-extract; do
        mv -f "$tarball" "$cache_dir/${tarball%%\?no-extract}"
    done
}

patch -p1 < llvm-clang.patch
patch -p1 < libressl.patch

# We modified vendored files here.
sed -i 's/\("files":{\)[^}]*/\1/' vendor/openssl-sys/.cargo-checksum.json

cat > config.toml <<EOF
[build]
build           = "x86_64-unknown-linux-musl"
host            = [ "x86_64-unknown-linux-musl" ]
target          = [ "x86_64-unknown-linux-musl" ]
docs            = false
compiler-docs   = false
extended        = true
submodules      = false
python          = "python3"
locked-deps     = true
vendor          = true
sanitizers      = false
profiler        = false
full-bootstrap  = false
cargo-native-static = true

[install]
prefix = "/usr"

[rust]
channel         = "stable"
rpath           = false
codegen-units   = 1
debuginfo-level = 0
backtrace       = false
jemalloc        = false
codegen-tests   = false
llvm-tools      = true
llvm-libunwind  = "system"

[target.x86_64-unknown-linux-musl]
llvm-config = "/usr/bin/llvm-config"
crt-static  = true
musl-root   = /usr
musl-libdir = /usr/lib
EOF

python3 ./x.py build -j "$(nproc)"
DESTDIR="$1" python3 ./x.py install

rm -rf "$1/usr/lib/rustlib/src/"
rm -f  "$1/usr/lib/rustlib/uninstall.sh"

# Install the license
install -Dm755 LICENSE-MIT    "$1/usr/share/LICENSES/rust-mit.license"
install -Dm755 LICENSE-APACHE "$1/usr/share/LICENSES/rust-apache.license"
