#!/bin/sh -e

(
    cd fuse2

    ./configure \
        --prefix=/ \
        --bindir=/bin \
        --sbindir=/bin \
        --datarootdir=/share \
        --disable-example \
        --disable-shared \
        MOUNT_FUSE_PATH=/usr/bin \
        UDEV_RULES_PATH=/usr/lib/udev

    make LDFLAGS="$LDFLAGS --static"
    make DESTDIR="$OLDPWD" install
)

export CFLAGS="$CFLAGS -Iinclude/fuse -Llib"
export PKG_CONFIG_PATH="$PWD/lib/pkgconfig"

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --disable-nls \
    --disable-rpath \
    --disable-shared \
    --disable-geoclue \
    --disable-libportal \
    --enable-static \
    --enable-pipewire

make PREFIX=/usr 
make PREFIX=/usr DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/xdg-desktop-portal.license"
