#!/bin/sh -e

sed -i 's/CC := gcc/CC := cc/' Makefile

make
make DESTDIR="$1" install

install -Dm755 usr/lib/hummingbird/* "$1/usr/lib/hummingbird"
install -Dm755 dist/kiss/*           "$1/usr/lib/hummingbird"

ln -s hummingbird "$1/usr/bin/init"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/hummingbird.license"
