#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -Wno-unused-command-line-argument"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libwebp.license"
