#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-libwebpmux \
    --enable-libwebpdemux \
    --enable-libwebpdecoder

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libwebp.license"
