#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -Wno-unused-command-line-argument"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -G Ninja

ninja -C build
ninja -C build install
