#!/bin/sh -e

export DESTDIR="$1"

sed -i 's/libgcc/libstdc++/' source/CMakeLists.txt

cmake source \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_TESTS=OFF \
    -DENABLE_SHARED=OFF \
    -DNATIVE_BUILD=ON \
    -Wno-dev -G Ninja -B build

ninja -C build
ninja -C build install
    #-DFPROFILE_USE=ON \
    #-DSTATIC_LINK_CRT=ON \
    #-DFPROFILE_GENERATE=ON \

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/x265.license"
