#!/bin/sh -e

pkg_dir=$1

make CC="${CC:-cc}"
make ZICDIR=/usr/bin DESTDIR="$1" install

set -- africa asia australasia europe northamerica southamerica

./zic -d "$pkg_dir/usr/share/zoneinfo"                      "$@"
./zic -d "$pkg_dir/usr/share/zoneinfo/posix"                "$@"
./zic -d "$pkg_dir/usr/share/zoneinfo/right" -L leapseconds "$@"
./zic -d "$pkg_dir/usr/share/zoneinfo"       -p America/New_York

# Install the license
install -Dm644 LICENSE "$DESTDIR/usr/share/LICENSES/tzdata.license"
