#!/bin/sh -e

patch -p1 < fix-dlo.patch

./configure \
    --prefix=/usr \
    --without-debug \
    --enable-static \
    --disable-shared

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/alsa-lib.license"
