#!/bin/sh -e

patch -p1 < fix-dlo.patch

./configure \
    --prefix=/usr \
    --without-debug \
    --enable-static \
    --disable-shared

make LDFLAGS="$LDFLAGS --static"
make DESTDIR="$1" install
