#!/bin/sh -e

sed -i '/\$(edit)\|\.\(service\|rules\)/d'   alsactl/Makefile.in
sed -i '/\$(edit)\|\.\(service\|rules\)/d'   alsaucm/Makefile.in
sed -i 's/ MIN_MENU_COMMAND/REQ_LEFT_ITEM/'  alsamixer/bindings.h
sed -i 's/ MAX_MENU_COMMAND/REQ_PREV_MATCH/' alsamixer/bindings.h

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-bat \
    --disable-nls \
    --disable-xmlto \
    --disable-alsaconf

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/alsa-utils.license"
