#!/bin/sh -e

sed -i '/\$(edit)\|\.\(service\|rules\)/d' alsactl/Makefile.in
sed -i '/\$(edit)\|\.\(service\|rules\)/d' alsaucm/Makefile.in

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --with-udev-rules-dir=/usr/lib/udev/rules.d \
    --disable-alsaconf \
    --disable-bat \
    --disable-xmlto \
    --disable-nls

make LDFLAGS="$LDFLAGS -lcurses"
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/alsa-utils.license"
