#!/bin/sh -e

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

./configure \
    --prefix=/usr \
    --without-debug

make
make DESTDIR="$1" install
make clean

./configure \
    --prefix=/usr \
    --without-debug \
    --disable-shared \
    --enable-static

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/alsa-lib.license"
