#!/bin/sh -e

patch -p1 < fix-dlo.patch

./configure \
    --prefix=/usr \
    --without-debug

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/alsa-lib.license"
