#!/bin/sh -e

patch -p1 < no-inline.patch
patch -p1 < fix-load_for_all_cards.patch

# Fix a missing include
sed -i '/<dirent.h>/a #include <linux/limits.h>' src/ucm/ucm_exec.c

./configure \
    --prefix=/usr \
    --without-debug

make 
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/alsa-lib.license"
