#!/bin/sh -e

export DESTDIR="$1"

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPUS_CUSTOM_MODES=ON \
    -DOPUS_CPU_X64=ON \
    -DBUILD_TESTING=OFF \
    -DBUILD_SHARED_LIBS=ON \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/opus.license"
