#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPUS_CUSTOM_MODES=ON \
    -DOPUS_CPU_X64=ON \
    -DBUILD_TESTING=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/opus.license"
