#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    -Ddocumentation=disabled \
    -Dtests=disabled \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libevdev.license"
