#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_JPEG8=1 \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm755 LICENSE.md "$1/usr/share/LICENSES/libjpeg-turbo.license"
