#!/bin/sh -e

export CARGO_HOME="$PWD"

(
    cd vendor

    for crate in *.crate; do
        tar xf "$crate"

        # Strip the filename form the sha256sum output
        sha256=$(sha256sum "$crate")
        sha256=${sha256%% *}

        printf '{"package":"%s","files":{}}\n' "$sha256" \
            > "${crate%.crate}/.cargo-checksum.json"
        done
)

mkdir -p .cargo

cat > .cargo/config << EOF
[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOF

rm -rf config

cargo build \
    --frozen \
    --release

install -Dm755 target/release/procs "$1/usr/bin/procs"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/procs.license"
