#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-asm \
    --disable-shared

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libass.license"
