#!/bin/sh -e

# We have an alternative system, use "ksh" and "sh" as binary names. 
./configure \
    --prefix=/usr \
    --bindir=/usr/bin \
    --mandir=/usr/share/man \
    --enable-ksh

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" install

# Install the license
install -Dm755 LEGAL "$1/usr/share/LICENSES/oksh.license"
