#!/bin/sh -e

# Because why not require EOL programs
mkdir -p bin
ln -sf /usr/bin/python2 "$1"/bin/python
ln -sf /usr/bin/python2-config "$1"/bin/python-config
export PATH="$1/bin:${PATH}"

npm install
npm run init

npm run build Release
