#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dtests=false \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/wayland-protocols.license"
