#!/bin/sh -e

# xz is Public Domain without GNU getopt.
# Configure checks for getopt.h, but I want to make sure it isn't built.
# If the make errors, you need GNU getopt.
rm -r lib/getopt*

./configure \
    --prefix=/usr \
    --disable-xz \
    --disable-doc \
    --disable-nls \
    --disable-xzdec \
    --disable-shared \
    --disable-lzmadec \
    --disable-scripts \
    --disable-lzmainfo \
    --disable-lzma-links

make
make DESTDIR="$1" install

# Delete empty directory
rmdir "$1/usr/bin"
