#!/bin/sh -e

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib

gmake
gmake PREFIX=/usr DESTDIR="$1" install

mkdir -p "$1/usr/bin"
ln -sf /usr/lib/ld-musl-x86_64.so.1 "$1/usr/bin/ldd"

# Install BSD compatibility headers.
cp -f cdefs.h queue.h tree.h \
    "$1/usr/include/sys"

# Install getconf.
cc getconf.c -o "$1/usr/bin/getconf"
cc getent.c  -o "$1/usr/bin/getent"

# Install the license
install -Dm644 COPYRIGHT "$1/usr/share/LICENSES/musl.license"
