#!/bin/sh -e

log() {
    printf '%s\n' "---  $3  ---"
    printf '%s %s %s\n' "$1" "${2##*/}" "${3##*/}"
}

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

FLAGS="-std=c99 -nostdinc -ffreestanding -frounding-math -Wa,--noexecstack     \
       -D_XOPEN_SOURCE=700 -I./arch/x86_64 -I./arch/generic -Iobj/src/internal \
       -I./src/include -I./src/internal -Iobj/include -I./include -pipe        \
       -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables \
       -ffunction-sections -fdata-sections -w $CFLAGS"

PICFLAGS="$FLAGS -fPIC"

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib

for dir in lib obj/crt/x86_64 obj/include/bits obj/ldso obj/src/aio          \
           obj/src/complex obj/src/conf obj/src/crypt obj/src/ctype          \
           obj/src/dirent obj/src/env obj/src/errno obj/src/exit             \
           obj/src/fcntl obj/src/fenv/x86_64 obj/src/internal obj/src/ipc    \
           obj/src/ldso/x86_64 obj/src/legacy obj/src/linux obj/src/locale   \
           obj/src/malloc/mallocng obj/src/math/x86_64 obj/src/misc          \
           obj/src/mman obj/src/mq obj/src/multibyte obj/src/network         \
           obj/src/passwd obj/src/prng obj/src/process/x86_64 obj/src/regex  \
           obj/src/sched obj/src/search obj/src/select obj/src/setjmp/x86_64 \
           obj/src/signal/x86_64 obj/src/stat obj/src/stdio obj/src/stdlib   \
           obj/src/string/x86_64 obj/src/temp obj/src/termios obj/src/unistd \
           obj/src/thread/x86_64 obj/src/time; do
    mkdir -p $dir
done

sed -f ./tools/mkalltypes.sed ./arch/x86_64/bits/alltypes.h.in ./include/alltypes.h.in > obj/include/bits/alltypes.h
cp arch/x86_64/bits/syscall.h.in obj/include/bits/syscall.h
sed -n -e s/__NR_/SYS_/p < arch/x86_64/bits/syscall.h.in >> obj/include/bits/syscall.h
printf '#define VERSION "%s"\n' "$(cd .; sh tools/version.sh)" > obj/src/internal/version.h

cc $PICFLAGS -fno-stack-protector -DCRT -c -o obj/crt/Scrt1.o crt/Scrt1.c
cc $FLAGS    -fno-stack-protector -DCRT -c -o obj/crt/crt1.o crt/crt1.c
cc $PICFLAGS -fno-stack-protector -DCRT -c -o obj/crt/rcrt1.o crt/rcrt1.c
cc $FLAGS    -fno-stack-protector -DCRT -c -o obj/crt/x86_64/crti.o crt/x86_64/crti.s
cc $FLAGS    -fno-stack-protector -DCRT -c -o obj/crt/x86_64/crtn.o crt/x86_64/crtn.s

cp obj/crt/Scrt1.o       lib/Scrt1.o
cp obj/crt/crt1.o        lib/crt1.o
cp obj/crt/rcrt1.o       lib/rcrt1.o
cp obj/crt/x86_64/crti.o lib/crti.o
cp obj/crt/x86_64/crtn.o lib/crtn.o

for file in src/aio/*.c src/complex/*.c src/conf/*.c src/crypt/*.c      \
    src/ctype/*.c src/dirent/*.c src/env/*.c src/errno/*.c src/exit/*.c \
    src/fcntl/*.c src/fenv/*.c src/fenv/x86_64/*.s src/internal/*.c     \
    src/ipc/*.c src/ldso/*.c src/ldso/x86_64/*.s src/legacy/*.c         \
    src/linux/*.c src/locale/*.c src/malloc/*.c src/malloc/mallocng/*.c \
    src/math/*.c src/math/x86_64/*.c src/math/x86_64/*.s src/misc/*.c   \
    src/mman/*.c src/mq/*.c src/multibyte/*.c src/network/*.c           \
    src/passwd/*.c src/prng/*.c src/process/*.c src/process/x86_64/*.s  \
    src/regex/*.c src/sched/*.c src/search/*.c src/select/*.c           \
    src/setjmp/x86_64/*.s src/signal/*.c src/signal/x86_64/*.s          \
    src/stat/*.c src/stdio/*.c src/stdlib/*.c src/string/*.c            \
    src/string/x86_64/*.s src/temp/*.c src/termios/*.c src/thread/*.c   \
    src/thread/x86_64/*.s src/time/*.c src/unistd/*.c; do
    case $file in
        src/fenv/fenv.c|src/ldso/dlsym.c|src/ldso/tlsdesc.c|\
        src/math/__invtrigl.c|src/math/acosl.c|src/math/asinl.c|\
        src/math/atan2l.c|src/math/atanl.c|src/math/ceill.c|\
        src/math/exp2l.c|src/math/expl.c|src/math/expm1l.c|\
        src/math/fabs.c|src/math/fabsf.c|src/math/fabsl.c|\
        src/math/floorl.c|src/math/fma.c|src/math/fmaf.c|\
        src/math/fmodl.c|src/math/llrint.c|src/math/llrintf.c|\
        src/math/llrintl.c|src/math/log10l.c|src/math/log1pl.c|\
        src/math/log2l.c|src/math/logl.c|src/math/lrint.c|\
        src/math/lrintf.c|src/math/lrintl.c|src/math/remainderl.c|\
        src/math/remquol.c|src/math/rintl.c|src/math/sqrt.c|\
        src/math/sqrtf.c|src/math/sqrtl.c|src/math/truncl.c|\
        src/process/vfork.c|src/signal/restore.c|src/signal/sigsetjmp.c|\
        src/string/memcpy.c|src/string/memmove.c|src/string/memset.c|\
        src/thread/__set_thread_area.c|src/thread/__unmapself.c|\
        src/thread/clone.c|src/thread/syscall_cp.c) ;; # Do Nothing
        src/env/__init_tls.c|src/env/__libc_start_main.c|\
        src/string/x86_64/memset.s|src/string/x86_64/memcpy.s|\
        src/thread/x86_64/__set_thread_area.s) # Stack Protected .s
            log CC ${file%%.s}.lo $file
            cc $FLAGS -fno-stack-protector -fPIC -c -o \
                obj/${file%%.s}.lo $file ;;
        src/env/__stack_chk_fail.c) # Stack Protected .c
            log CC ${file%%.c}.lo $file
            cc $FLAGS -fno-stack-protector -fPIC -c -o \
                obj/${file%%.c}.lo $file ;;
        *.s) # S files
            log CC ${file%%.s}.lo $file
            cc $PICFLAGS -c -o obj/${file%%.s}.lo $file ;;
        *.c) # C files
            log CC ${file%%.c}.lo $file
            cc $PICFLAGS -c -o obj/${file%%.c}.lo $file ;;
    esac
done

ar rcs lib/libc.a obj/src/aio/*.lo obj/src/complex/*.lo                \
    obj/src/conf/*.lo obj/src/crypt/*.lo obj/src/ctype/*.lo            \
    obj/src/dirent/*.lo obj/src/env/*.lo obj/src/errno/*.lo            \
    obj/src/exit/*.lo obj/src/fcntl/*.lo obj/src/fenv/*.lo             \
    obj/src/fenv/x86_64/*.lo obj/src/internal/*.lo obj/src/ipc/*.lo    \
    obj/src/ldso/*.lo obj/src/ldso/x86_64/*.lo obj/src/legacy/*.lo     \
    obj/src/linux/*.lo obj/src/locale/*.lo obj/src/malloc/*.lo         \
    obj/src/malloc/mallocng/*.lo obj/src/math/*.lo                     \
    obj/src/math/x86_64/*.lo obj/src/misc/*.lo obj/src/mman/*.lo       \
    obj/src/mq/*.lo obj/src/multibyte/*.lo obj/src/network/*.lo        \
    obj/src/passwd/*.lo obj/src/prng/*.lo obj/src/process/*.lo         \
    obj/src/process/x86_64/vfork.lo obj/src/regex/*.lo                 \
    obj/src/sched/*.lo obj/src/search/*.lo obj/src/select/*.lo         \
    obj/src/setjmp/x86_64/*.lo obj/src/signal/*.lo                     \
    obj/src/signal/x86_64/*.lo obj/src/stat/*.lo obj/src/stdio/*.lo    \
    obj/src/stdlib/*.lo obj/src/string/*.lo obj/src/string/x86_64/*.lo \
    obj/src/temp/*.lo obj/src/termios/*.lo obj/src/thread/*.lo         \
    obj/src/thread/x86_64/*.lo obj/src/time/*.lo obj/src/unistd/*.lo

cc $FLAGS -fno-stack-protector -fPIC -c -o obj/ldso/dlstart.lo ldso/dlstart.c
cc $FLAGS -fno-stack-protector -fPIC -c -o obj/ldso/dynlink.lo ldso/dynlink.c

cc $FLAGS -Wl,--sort-section,alignment -Wl,--sort-common                \
    -Wl,--gc-sections -Wl,--hash-style=both -Wl,--no-undefined          \
    -Wl,--exclude-libs=ALL -Wl,--dynamic-list=./dynamic.list -nostdlib  \
    -shared -Wl,-e,_dlstart -o lib/libc.so obj/src/aio/*.lo             \
    obj/src/complex/*.lo obj/src/conf/*.lo obj/src/crypt/*.lo           \
    obj/src/ctype/*.lo obj/src/dirent/*.lo obj/src/env/*.lo             \
    obj/src/errno/*.lo obj/src/exit/*.lo obj/src/fcntl/*.lo             \
    obj/src/fenv/*.lo obj/src/fenv/x86_64/*.lo obj/src/internal/*.lo    \
    obj/src/ipc/*.lo obj/src/ldso/*.lo obj/src/ldso/x86_64/*.lo         \
    obj/src/legacy/*.lo obj/src/linux/*.lo obj/src/locale/*.lo          \
    obj/src/malloc/*.lo obj/src/malloc/mallocng/*.lo obj/src/math/*.lo  \
    obj/src/math/x86_64/*.lo obj/src/misc/*.lo obj/src/mman/*.lo        \
    obj/src/mq/*.lo obj/src/multibyte/*.lo obj/src/network/*.lo         \
    obj/src/passwd/*.lo obj/src/prng/*.lo obj/src/process/*.lo          \
    obj/src/process/x86_64/vfork.lo obj/src/regex/*.lo                  \
    obj/src/sched/*.lo obj/src/search/*.lo obj/src/select/*.lo          \
    obj/src/setjmp/x86_64/*.lo obj/src/signal/*.lo                      \
    obj/src/signal/x86_64/*.lo obj/src/stat/*.lo obj/src/stdio/*.lo     \
    obj/src/stdlib/*.lo obj/src/string/*.lo obj/src/string/x86_64/*.lo  \
    obj/src/temp/*.lo obj/src/termios/*.lo obj/src/thread/*.lo          \
    obj/src/thread/x86_64/*.lo obj/src/time/*.lo obj/src/unistd/*.lo    \
    obj/ldso/dlstart.lo obj/ldso/dynlink.lo                             \
    /usr/lib/clang/12.0.1/lib/linux/libclang_rt.builtins-x86_64.a

for lib in m rt pthread crypt util xnet resolv dl; do
    ar rc "lib/lib${lib}.a"
done

for lib in Scrt1.o crt1.o rcrt1.o crti.o crtn.o libc.a libm.a librt.a \
    libpthread.a libcrypt.a libutil.a libxnet.a libresolv.a libdl.a; do
    install -Dm644 "lib/$lib" "$1/usr/lib/$lib"
done

# Special lib
install -Dm755 lib/libc.so $1/usr/lib/libc.so

for hdr in include/*.h include/netpacket/*.h include/netinet/*.h      \
    include/arpa/*.h include/net/*.h include/scsi/*.h include/sys/*.h \
    arch/x86_64/bits/*.h arch/generic/bits/*.h obj/include/bits/*.h; do
    case $hdr in
        */bits/*) install -Dm644 $hdr "$1/usr/include/bits/${hdr##*/}" ;;
        *)        install -Dm644 $hdr "$1/usr/$hdr"                    ;;
    esac
done

mkdir -p "$1/usr/bin"
ln -sf /usr/lib/ld-musl-x86_64.so.1 "$1/usr/bin/ldd"

# Create canonical symlink
ln -sf libc.so "$1/usr/lib/ld-musl-x86_64.so.1"

# Install BSD compatibility headers.
cp -f cdefs.h queue.h tree.h \
    "$1/usr/include/sys"

# Install getconf.
cc getconf.c -o "$1/usr/bin/getconf"
cc getent.c  -o "$1/usr/bin/getent"

# Install the license
install -Dm755 COPYRIGHT "$1/usr/share/LICENSES/musl.license"
