#!/bin/sh -e

export DESTDIR="$1"

fixHead=subprojects/fcft
install -Dm644 "$fixHead/fcft.h"   "$fixHead/fcft/fcft.h"
install -Dm644 "$fixHead/stride.h" "$fixHead/fcft/stride.h"

# Note to self: always make doc generation toggleable
sed -i "/subdir('doc')/d" meson.build

meson \
    --prefix=/usr \
    --buildtype=debug \
    . build

ninja -C build
ninja -C build install

# Install terminfo because duh
mkdir -p "$1/usr/share/terminfo/f"

cp build/f/foot        "$1/usr/share/terminfo/f/foot"
cp build/f/foot-direct "$1/usr/share/terminfo/f/foot-direct"
