#!/bin/sh -e

patch -p1 < static.patch

# For static building
export CFLAGS="$CFLAGS -static -l:libffi.a"
export CC=/usr/bin/cc

# Note to self: always make doc generation toggleable
sed -i "/subdir('doc')/d" meson.build

meson \
    --prefix=/usr \
    --buildtype=release \
    . build

ninja -C build
ninja -C build install

# Install terminfo because duh
mkdir -p "$1/usr/share/terminfo/f"

cp build/f/foot        "$1/usr/share/terminfo/f/foot"
cp build/f/foot-direct "$1/usr/share/terminfo/f/foot-direct"
