#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --with-privsep-user=openntpd \
    --with-cacert=/etc/ssl/cert.pem

make
make DESTDIR="$1" install

install -Dm755 ntpd.run "$1/etc/s6-rc/scripts/openntpd.boot"

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/openntpd.license"
