#!/bin/sh -e

sed -i '/assembler-with-cpp/s%\$<%$(top_srcdir)/libffi.map.in%' Makefile.in

./configure \
    --prefix=/usr \
    --disable-shared

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/info"
