#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

sed -i '/assembler-with-cpp/s%\$<%$(top_srcdir)/libffi.map.in%' Makefile.in

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/info"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/libffi.license"
