#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIBXML2_WITH_DEBUG=OFF \
    -DLIBXML2_WITH_LEGACY=OFF \
    -DLIBXML2_WITH_PYTHON=OFF \
    -DLIBXML2_WITH_TESTS=OFF \
    -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libxml2.license"
