#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-threads \
    --with-history \
    --without-icu \
    --without-debug \
    --without-legacy \
    --without-python

gmake
gmake PREFIX=/usr DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libxml2.license"
