#!/bin/sh -e

# Don't build hikari-unlocker
sed -i 's/hikari hikari-unlocker/hikari/g'  Makefile

make \
    PREFIX=/usr \
    ETC_PREFIX=/ \
    with_SCREEN_COPY=YES \
    WITH_POSIX_C_SOURCE=YES \
    PKG_CONFIG="pkg-config --static"

install -Dm755 hikari "$1/usr/bin/hikari"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/hikari.license"
