#!/bin/sh -e

for patch in *.patch; do 
    patch -p1 < "$patch"
done

make
    PREFIX=/usr \
    ETC_PREFIX=/ \
    WITH_POSIX_C_SOURCE=YES \
    WITH_LAYERSHELL=YES \
    WITH_SCREENCOPY=YES

make \
    PREFIX=/usr \
    ETC_PREFIX=/ \
    DESTDIR="$1" \
    install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/hikari.license"
