#!/bin/sh -e

install -Dm644 cozette.otb       "$1/usr/share/fonts/misc/cozette.otb"
install -Dm644 CozetteVector.ttf "$1/usr/share/fonts/TTF/CozetteVector.ttf"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/cozette-font.license"
