#!/bin/sh -e

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')

./configure \
    --prefix=/usr \
    --static

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYRIGHT-BSD2.txt "$1/usr/share/LICENSES/fossil.license"
