#!/bin/sh -e

gmake \
    LDFLAGS="$LDFLAGS -static" \
    DESTDIR="$1" \
    PREFIX=/usr \
    all-static \
    install-static

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/netbsd-curses.license"
