#!/bin/sh -e

patch -p1 < CVE-2016-9296.patch
patch -p1 < CVE-2017-17969.patch
patch -p1 < CVE-2018-10115.patch
patch -p1 < CVE-2018-5996.patch

cp makefile.linux_amd64_asm makefile.machine
make all3 OPTFLAGS="$CFLAGS"

make install DEST_DIR="$1" DEST_HOME=/usr

rm -r "$1/usr/share/doc/p7zip/DOC/MANUAL/fm"

install -d "$1"/usr/share/licenses/97zip
