#!/bin/sh -e 

sed -i 's/perl -pe/sed -e/g' configure

./configure \
    --prefix=/usr \
    -t openmp \
    auto

make
make DESTDIR="$1" install

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/blis.license"
