#!/bin/sh -e

mkdir -pv build
cd build

cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local \
        -DLLVM_CONFIG=${HOME}/.local/bin/llvm-config \
        -DLLVM_TARGETS_TO_BUILD=X86 \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        ..

make

make DESTDIR="$1" install
