#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DGLM_TEST_ENABLE=FALSE

cmake --build   build

mkdir -p "$1/usr/include"
cp -r glm "$1/usr/include"

install -Dm644 glm.pc "$1/usr/lib/pkgconfig/glm.pc"
