#!/bin/sh -e

export DESTDIR="$1"

CFLAGS=$(printf %s "$CFLAGS" | sed 's/-static//')

meson \
	--prefix=/usr \
    -Dshcompletiondir=no \
	. build

ninja -C build
ninja -C build install

rm -rf "$1/usr/share/zsh/"
rm -rf "$1/usr/share/bash-completion/"

cd wl-clipboard-x11/src

install -Dm755 wl-clipboard-x11 "$1/usr/bin/wl-clipboard-x11"
ln -s /usr/bin/wl-clipboard-x11 "$1/usr/bin/xclip"
ln -s /usr/bin/wl-clipboard-x11 "$1/usr/bin/xsel"
