#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/-scanner', /-scanner', static: true, /"     src/meson.build
sed -i "s/-protocols', /-protocols', static: true, /" src/meson.build

meson \
    --prefix=/usr \
    -Dzshcompletiondir=no \
    . build

ninja -C build
ninja -C build install

install -Dm755 wl-clipboard-x11/src/wl-clipboard-x11 "$1/usr/bin/wl-clipboard-x11"

ln -s wl-clipboard-x11 "$1/usr/bin/xclip"
ln -s wl-clipboard-x11 "$1/usr/bin/xsel"
