#!/bin/sh -e

make CC="${CC:-cc} $CFLAGS -fPIC $LDFLAGS" -f Makefile-libbz2_so
make CC="${CC:-cc} $CFLAGS -fPIC $LDFLAGS"

for bin in bzip2 bzdiff bzgrep bzip2recover bzmore; do
    install -Dm755 "$bin" "$1/usr/bin/$bin"
done
 
install -Dm755 libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0.8"
install -Dm644 libbz2.a        "$1/usr/lib/libbz2.a"
install -Dm644 bzip2.1         "$1/usr/share/man/man1/bzip2.1"
install -Dm644 bzlib.h         "$1/usr/include/bzlib.h"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/bzip2.license"
