#!/bin/sh -e

for patch in *.patch; do 
    patch -p1 < $patch
done

make -f unix/Makefile \
    CC="${CC:-cc}" \
    LOCAL_UNZIP="$CFLAGS $CPPFLAGS -DNO_LCHMOD" \
    prefix=/usr generic

make -f unix/Makefile \
    MANDIR="$1/usr/share/man/man1" \
    prefix="$1/usr" install
