#!/bin/sh -e

./configure \
    --pkg-config-flags=--static \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --prefix=/usr \
    --x86asmexe=nasm \
    --enable-gpl \
    --enable-lto \
    --enable-libass \
    --enable-libdrm \
    --enable-libvpx \
    --enable-nonfree \
    --enable-openssl \
    --enable-libopus \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-version3 \
    --enable-libvorbis \
    --enable-libmp3lame \
    --disable-doc \
    --disable-debug \
    --disable-shared \
    --disable-libxml2 \
    --disable-manpages \
    --disable-podpages \
    --disable-txtpages \
    --disable-htmlpages \
    --disable-large-tests

gmake
gmake DESTDIR="$1" install

# Remove examples.
rm -rf "$1/usr/share/ffmpeg/examples"

# Install the license
install -Dm755 COPYING.GPLv2  "$1/usr/share/LICENSES/ffmpeg-gplv2.license"
install -Dm755 COPYING.GPLv3  "$1/usr/share/LICENSES/ffmpeg-gplv3.license"
install -Dm755 COPYING.LGPLv3 "$1/usr/share/LICENSES/ffmpeg-lgplv3.license"
