#!/bin/sh -e

./configure \
    --pkg-config-flags=--static \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --prefix=/usr \
    --x86asmexe=nasm \
    --enable-gpl \
    --enable-version3 \
    --enable-nonfree \
    --enable-openssl \
    --enable-libass \
    --enable-libdrm \
    --enable-libvpx \
    --enable-static \
    --enable-libopus \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-libvorbis \
    --enable-libmp3lame \
    --disable-libxml2 \
    --disable-large-tests \
    --disable-doc \
    --disable-debug \
    --disable-shared \
    --disable-ffprobe \
    --disable-manpages \
    --disable-podpages \
    --disable-txtpages \
    --disable-htmlpages

gmake
gmake DESTDIR="$1" install

# Remove examples.
rm -rf "$1/usr/share/ffmpeg/examples"
