#!/bin/sh -e

export DESTDIR="$1"

sed -i "s|fontconfig'|fontconfig', static: true|" meson.build
sed -i "s|freetype2'|freetype2', static: true|"   meson.build
sed -i "s|pixman-1'|pixman-1', static: true|"     meson.build
sed -i "s|harfbuzz'|harfbuzz', static: true|"     meson.build
sed -i "s|threads'|threads', static: true|"       meson.build

install -Dm644 fcft.h   fcft/fcft.h
install -Dm644 stride.h fcft/stride.h

# Note to self: always make doc generation toggleable
sed -i "s|subdir('doc')||" meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=static \
    -Dbuildtype=release \
    . build

ninja -C build
ninja -C build install

install -Dm755 LICENSE "$1/usr/share/LICENSES/fcft.license"
