#!/bin/sh -e 

./configure \
        --prefix=/usr \
        --with-intl=system-icu \
        --shared-libressl \
        --shared-zlib \
        --shared-libuv \
        --experimental-http-parser \
        --shared-cares \
        --shared-nghttp2

make V= \
        DESTCPU="x64" \
        ARCH="x64" \
        VARIATION="musl"

make DESTDIR="$1" install
