#!/bin/sh -e 

export 'CC=ccache gcc'
CC='ccache gcc'
export 'CXX=ccache g++'
CXX='ccache g++'

python ./configure \
        --prefix=/usr \
        --dest-cpu=x64 \
        --with-intl=system-icu \
#        --shared-openssl \
        --shared-zlib \
        --shared-libuv \
#        --experimental-http-parser \
        --shared-cares \
        --shared-nghttp2

make \
        DESTCPU=x64 \
        ARCH=x64 \
        VARIATION=musl
        DISTTYPE=release

make DESTDIR="$1" install
