#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --without-python

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libcap-ng.license"
