#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --buildtype=release \
    -Denable_docs=false \
    -Dwith_glx=no \
    -Dwith_x11=no \
    -Dwith_wayland=yes \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/libva.license"
