#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < evdev-wrap.patch

(
    cd evdev
    export DESTDIR="$OLDPWD"

    meson \
        --prefix=/usr \
        --buildtype=release \
        -Ddefault_library=static \
        -Ddocumentation=disabled \
        -Dtests=disabled \
        . build

    ninja -C build
    ninja -C build install

    # Install the license
    install -Dm644 COPYING "$1/usr/share/LICENSES/libevdev.license"
)

(
    cd mtdev
    export DESTDIR="$OLDPWD"

    ./configure \
        --prefix=/usr \
        --disable-shared \
        --disable-gcov

    make
    make install

    # Install the license
    install -Dm644 COPYING "$1/usr/share/LICENSES/mtdev.license"
)

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

export PKG_CONFIG_PATH="$PWD/usr/lib/pkgconfig"
export CFLAGS="$CFLAGS -I$PWD/usr/include -L$PWD/usr/lib"
export CFLAGS="$CFLAGS -I$PWD/usr/include/libevdev-1.0"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    --buildtype=release \
    -Ddefault_library=both \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/libinput.license"
