#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < evdev-wrap.patch

(
cd evdev

meson \
    --prefix=/usr \
    --buildtype=release \
    -Ddocumentation=disabled \
    -Dtests=disabled \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libevdev.license"
)

(
cd mtdev

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/mtdev.license"
)

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

export PKG_CONFIG_PATH="$PWD/usr/lib/pkgconfig"
export CFLAGS="$CFLAGS -I$PWD/usr/include -L$PWD/usr/lib"
export CFLAGS="$CFLAGS -I$PWD/usr/include/libevdev-1.0"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    --buildtype=release \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/libinput.license"
