#!/bin/sh -e

# Disable warning because we don't want expansion
#shellcheck disable=2016
sed -i 's/ | \$(FLEX)$//' doc/Makefile.in

./configure \
    --prefix=/usr \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$1" install

ln -s flex "$1/usr/bin/lex"

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/flex.license"
