#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddefault_library=both \
    -Dglx=no \
    -Degl=yes \
    -Dx11=false \
    -Dtests=false \
    . build

ninja -C build
ninja -C build install
