#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dhas-dlvsym=false \
    -Dx11=false \
    . build

ninja -C build
ninja -C build install
