#!/bin/sh -e

for file in libnl/*.c; do
    "${CC:-cc}" $CFLAGS -fPIC -Ilibnl/include -c -o "${file%%.c}.o" "$file"
done

ar rcs libnl/libnl-tiny.a libnl/*.o

export CFLAGS="$CFLAGS -I$PWD/libnl/include -L$PWD/libnl \
               -static -D_GNU_SOURCE -DLIBNL1_COMPAT \
               -Wno-unused-command-line-argument"

cd wpa_supplicant

make PREFIX=/usr
make PREFIX=/usr DESTDIR="$1" install

install -Dm755 wpa_supplicant.run "$1/etc/sysmgr/wpa_supplicant"

# Install the license
install -Dm755 ../COPYING "$1/usr/share/LICENSES/wpa_supplicant.license"
