#!/bin/sh -e

# The wpa_supplicant package is built statically using
# libnl-tiny which is a minimal version of libnl maintained
# by OpenWRT.
mv libnl-tiny* libnl.tar.gz
tar xzf libnl.tar.gz
mv libnl-tiny* libnl

export CFLAGS="$CFLAGS -D_GNU_SOURCE -I$PWD/libnl/include"
export LDFLAGS="$LDFLAGS -L$PWD/libnl"

(
    cd libnl

    # CFLAGS must expand to individual arguments.
    # shellcheck disable=2086
    ${CC:-cc} $CFLAGS $CPPFLAGS -c ./*.c
    ${AR:-ar} rc libnl-tiny.a ./*.o
)

cd wpa_supplicant

gmake LIBDIR=/usr/lib BINDIR=/usr/bin
gmake LIBDIR=/usr/lib BINDIR=/usr/bin DESTDIR="$1" install

install -Dm755 wpa_supplicant.run "$1/etc/sysmgr/wpa_supplicant"

# Install the license
install -Dm644 ../COPYING "$1/usr/share/LICENSES/wpa_supplicant.license"
