#!/bin/sh -e

sed -i 's/bash/sh/' configure

./configure \
    --prefix=/usr \
    --zlib-compat \
    --native

gmake
gmake DESTDIR="$1" install

# Install the license
install -Dm755 LICENSE.md "$1/usr/share/LICENSES/zlib.license"
