#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-unicode-properties

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/doc"

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/pcre.license"
