#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    source -G Ninja

ninja -C build
ninja -C build install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/x265.license"
