#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-system-zlib

make doas patch pax LDFLAGS="$LDFLAGS -static"

install -Dm755 pax   "$1/usr/bin/pax"
install -Dm755 doas  "$1/usr/bin/doas"
install -Dm755 patch "$1/usr/bin/patch"

# pax replaces tar, cpio
ln -sf pax "$1/usr/bin/tar"
ln -sf pax "$1/usr/bin/cpio"

# doas needs setuid, nice conf
chmod gu+s "$1/usr/bin/doas"

install -Dm600 doas.conf "$1/etc/doas.conf"

# Install the license
install -Dm755 README.md "$1/usr/share/LICENSES/pax.license"
