#!/bin/sh -e

build_freetype() (

    cd freetype

    export DESTDIR="$1"

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DFT_WITH_PNG=ON \
        -DFT_WITH_HARFBUZZ="$2" \
        -Wno-dev -G Ninja
    
    ninja -C build
    ninja -C build install
)

build_harfbuzz() (

    export DESTDIR="$1"

    # Point Harfbuzz to the Freetype files.
    export CFLAGS="$CFLAGS -I$1/usr/include/freetype2"
    export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
    export LDFLAGS="$LDFLAGS -L$1/usr/lib"

    cd harfbuzz

    patch -p1 < ../static.patch

        #-Ddefault_library=static \
    meson \
        --prefix=/usr \
        -Dpkg_config_path="$1/usr/lib/pkgconfig" \
        -Dbuildtype=release \
        -Ddefault_library=static \
        -Dfreetype=enabled \
        -Dcairo=disabled \
        -Dglib=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . build

    ninja -C build
    ninja -C build install
)

build_freetype "$1" OFF
build_harfbuzz "$1"

# Point Freetype to the Harfbuzz files.
export HARFBUZZ_CFLAGS="-I$PWD/harfbuzz/src"
export HARFBUZZ_LIBS="-L$PWD/harfbuzz/build/src -lharfbuzz"

build_freetype "$1" ON
