#!/bin/sh -e

export DESTDIR="$1"

build_freetype() (
    cd freetype

    meson \
        --prefix=/usr \
        -Ddefault_library=both \
        -Dbzip2=disabled \
        -Dzlib=disabled \
        "$@" \
        . build

    ninja -C build
    ninja -C build install
)

# No it doesn't
# shellcheck disable=2120
build_harfbuzz() (
    cd harfbuzz

    meson \
        --prefix=/usr \
        -Dpkg_config_path="$1/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . build

    ninja -C build
    ninja -C build install
)

# Point Freetype to the Harfbuzz files.
export CFLAGS="$CFLAGS -I$1/usr/include/harfbuzz"
export CFLAGS="$CFLAGS -L$1/usr/lib "
export PKG_CONFIG_PATH="$1/usr/lib/pkgconfig"

# Point Harfbuzz to the Freetype files.
export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
export CXXFLAGS="$CXXFLAGS -L$1/usr/lib"

build_freetype -Dharfbuzz=disabled
build_harfbuzz
build_freetype -Dharfbuzz=enabled --reconfigure

# Install the license file
install -Dm644 harfbuzz/COPYING      "$1/usr/share/LICENSES/harfbuzz.license"
install -Dm644 freetype/docs/FTL.TXT "$1/usr/share/LICENSES/freetype.license"
