#!/bin/sh -e

build_freetype() (

    cd freetype

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DFT_WITH_BROTLI=OFF \
        -DFT_WITH_HARFBUZZ="$2" \
        -G Ninja

    ninja -C build
    ninja -C build install
)

build_harfbuzz() (

    # Point Harfbuzz to the Freetype files.
    export CFLAGS="$CFLAGS -I$1/usr/include/freetype2"
    export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
    export LDFLAGS="$LDFLAGS -L$1/usr/lib"

    cd harfbuzz

    meson \
        --prefix=/usr \
        --buildtype=release \
        -Dpkg_config_path="$1/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dfreetype=enabled \
        -Dcairo=disabled \
        -Dglib=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . build

    ninja -C build
    ninja -C build install
)

export DESTDIR="$1"

build_freetype "$1" OFF
build_harfbuzz "$1"

# Point Freetype to the Harfbuzz files.
export HARFBUZZ_CFLAGS="-I$PWD/harfbuzz/src"
export HARFBUZZ_LIBS="-L$PWD/harfbuzz/build/src -lharfbuzz"

build_freetype "$1" ON

# Install the license
install -Dm755 harfbuzz/COPYING          "$1/usr/share/LICENSES/harfbuzz.license"
install -Dm755 freetype/docs/LICENSE.TXT "$1/usr/share/LICENSES/freetype.license"
