#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dbuildtype=release \
    -Ddocs=false \
    -Dtests=false \
    -Ddeprecated=false \
    . build

ninja -C build
ninja -C build install
