#!/bin/sh -e

# Swap to shell script instead of perl script
# for conversion of rules files. See files/xml2lst.
sed -i 's/perl //;s/xml2lst\.pl/xml2lst/' rules/Makefile.in

./configure \
    --prefix=/usr \
    --with-xkb-rules-symlink=xfree86,xorg \
    --enable-compat-rules \
    --without-xsltproc \
    --disable-nls \
    --disable-runtime-deps

gmake
gmake DESTDIR="$1" install

# To evade libX11 and its deps, we will carry around our own locale files.
cd libX11/nls
./gen_compose "$1/usr/share/X11/locale"
