#!/bin/sh -e

export DESTDIR="$1"

sed -i '/^perl/d'               rules/meson.build
sed -i 's/xml2lst\.pl/xml2lst/' rules/meson.build

meson \
    --prefix=/usr \
    --buildtype=release \
    -Derrorlogs=false \
    -Dstdsplit=false \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/xkeyboard-config.license"
