#!/bin/sh -e

export DESTDIR="$1"

# The meson project is under the impression that
# freetype isn't on major version 6...
sed -i 's/21.0.15/2.10.4/' meson.build

meson \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --buildtype=release \
    -Ddefault_library=both \
    -Ddoc=disabled \
    -Dnls=disabled \
    -Dtests=disabled \
    -Ddoc-pdf=disabled \
    -Ddoc-man=disabled \
    -Ddoc-txt=disabled \
    -Ddoc-html=disabled \
    . build

ninja -C build
ninja -C build install

install -Dm755 COPYING "$1/usr/share/LICENSES/fontconfig.license"
