#!/bin/sh -e

# Make the build system run /bin/true to generate
# a dummy file so our pre-generated one is used.
sed -i 's/fcobjshash\.h/fcjunk.h/' src/Makefile.in

./configure \
    GPERF=/bin/true \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts \
    --enable-static \
    --disable-docs \
    --disable-nls

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/fontconfig.license"
