#!/bin/sh -e

export DESTDIR="$1"

for patch in *.patch; do 
    patch -p1 < "$patch"
done

meson \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    -Dbuildtype=release \
    -Ddefault_library=static \
    -Ddoc=disabled \
    -Dnls=disabled \
    -Dtests=disabled \
    -Ddoc-pdf=disabled \
    -Ddoc-man=disabled \
    -Ddoc-txt=disabled \
    -Ddoc-html=disabled \
    . build

# ...Broken?
rm install-cache.py

ninja -C build
ninja -C build install
