#!/bin/sh -e

gmake \
    PREFIX=/usr \
    CC=cc \
    ENABLE_DEBUG=0

gmake \
    PREFIX=/usr \
    CC=cc \
    DESTDIR="$1" install

# Install a sample conf
install -Dm755 velox.conf.sample "$1/etc/velox.conf"
