#!/bin/sh -e

# Remove rsync dependency
patch -p1 < rsyncless.patch

# Perhaps we try clang on for size
rm -f .clang

# Set the kernel up for success!
scripts/setlocalversion --save-scmversion
cp config .config

make \
    olddefconfig \
    HOSTCC=clang \
    CC=clang

make \
    headers_install \
    INSTALL_HDR_PATH="$1" \
    HOSTCC=clang \
    CC=clang
