#!/bin/sh -e

export DESTDIR="$1"

sed -i "s/pciaccess', /pciaccess', static: true, /" meson.build
sed -i "s/shared_library/static_library/"           intel/meson.build
sed -i "s/shared_library/static_library/"           meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=static \
    -Dbuildtype=release \
    -Dintel=true \
    -Dlibkms=false \
    -Dvmwgfx=false \
    -Dradeon=false \
    -Damdgpu=false \
    -Dnouveau=false \
    . build

ninja -C build
ninja -C build install
