#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    -Dbuildtype=release \
    -Damdgpu=true \
    -Dradeon=true \
    -Dintel=false \
    -Dlibkms=false \
    -Dvmwgfx=false \
    -Dnouveau=false \
    . build

ninja -C build
ninja -C build install
