#!/bin/sh -e

patch -p1 < cmake-no-execinfo.patch

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

if command -v cmake >/dev/null; then
    export DESTDIR="$1"

    cmake -B build \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_USE_SYSTEM_CURL=True \
        -DCMAKE_USE_SYSTEM_ZLIB=True \
        -DCMAKE_USE_SYSTEM_ZSTD=True \
        -DCMAKE_USE_SYSTEM_BZIP2=True \
        -DCMAKE_USE_SYSTEM_EXPAT=True \
        -DCMAKE_USE_SYSTEM_LIBLZMA=True \
        -DBUILD_TESTING=False

    cmake --build   build
    cmake --install build

else
    ./configure \
        --prefix=/usr \
        --system-curl \
        --system-zlib \
        --system-zstd \
        --system-bzip2 \
        --system-expat \
        --system-liblzma \
        -- -DBUILD_TESTING=False

    make

    make DESTDIR="$1" install
fi

rm -rf "$1/usr/doc"
rm -rf "$1/usr/share/cmake*/Help"

# Install the license
install -Dm644 Copyright.txt "$1/usr/share/LICENSES/cmake.license"
