#!/bin/sh

cd runtime/libpgmath
mkdir -pv build
cd build

cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local \
        -DLLVM_CONFIG=${HOME}/.local/bin/llvm-config \
        -DCMAKE_CXX_COMPILER=${HOME}/.local/bin/clang++ \
        -DCMAKE_C_COMPILER=${HOME}/.local/bin/clang \
        -DCMAKE_Fortran_COMPILER=${HOME}/.local/bin/flang \
        -DLLVM_TARGETS_TO_BUILD=X86 \
        ..

make

make DESTDIR="$1" install

cd ../..
mkdir -pv build
cd build

cmake -DCMAKE_INSTALL_PREFIX=${HOME}/.local \
        -DLLVM_CONFIG=${HOME}/.local/bin/llvm-config \
        -DCMAKE_CXX_COMPILER=${HOME}/.local/bin/clang++ \
        -DCMAKE_C_COMPILER=${HOME}/.local/bin/clang \
        -DCMAKE_Fortran_COMPILER=${HOME}/.local/bin/flang \
        -DLLVM_TARGETS_TO_BUILD=X86 \
        ..

make

make DESTDIR="$1" install
