#!/bin/sh -e

make PREFIX=/usr LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" PREFIX=/usr install

rm "$1/usr/lib/libudev.so" "$1/usr/lib/libudev.so.1"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/libudev-zero.license"
