#!/bin/sh -e

make PREFIX=/usr
make PREFIX=/usr DESTDIR="$1" install

cc -o helper contrib/helper.c

install -Dm755 helper "$1/usr/bin/helper"

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/libudev-zero.license"
