#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-smack \
    --disable-selinux \
    --disable-rightleft \
    --disable-arabic \
    --disable-gtk2-check \
    --disable-gtk3-check \
    --disable-motif-check \
    --disable-athena-check \
    --disable-nextaw-check \
    --disable-gtktest \
    --disable-icon-cache-update \
    --disable-desktop-database-update \
    --disable-canberra \
    --disable-acl \
    --disable-nls \
    --enable-terminal \
    --with-features=big

make LDFLAGS="$LDFLAGS -static"
make DESTDIR="$1" install

cp -r runtime/* "$1/usr/share/vim/vim90"

# Install the license
install -Dm644 LICENSE "$1/usr/share/LICENSES/vim.license"
