#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-shared \
    --disable-gssapi

make
make DESTDIR="$1" install

# Install the license
install -Dm644 COPYING "$1/usr/share/LICENSES/libtirpc.license"
