#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

gmake \
    libdir=/usr/lib/ \
    bindir=/usr/bin/ \
    mandir=/usr/share/man/ \
    includedir=/usr/include/ \
    CC="${CC:-cc}" \
    AR="${AR:-ar}" \
    static

# Install all our garbage

mkdir -p "$1/usr/lib/pkgconfig" "$1/usr/include"
cp -r src/include/efivar "$1/usr/include/efivar"

cat >> "$1/usr/lib/pkgconfig/efivar.pc" << EOF
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/
includedir=/usr/include/

Name: efivar
Description: UEFI Variable Management
Version: $2
Libs: -L/usr/lib -lefivar
Libs.private: -ldl
Cflags: -I/usr/include/efivar
EOF

cat >> "$1/usr/lib/pkgconfig/efiboot.pc" << EOF
prefix=/usr
exec_prefix=/usr
libdir=/usr/lib/
includedir=/usr/include/

Name: efiboot
Description: UEFI Boot variable support
Version: $2
Requires.private: efivar
Libs: -L/usr/lib -lefiboot
Cflags: -I/usr/include/efivar
EOF

install -Dm755 src/efivar-static "$1/usr/bin/efivar"
install -Dm644 src/libefivar.a   "$1/usr/lib/libefivar.a"
install -Dm644 src/libefiboot.a  "$1/usr/lib/libefiboot.a"
