#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

(
    cd common/sys
    m4 -DSRCDIR=$PWD elfdefinitions.m4 > elfdefinitions.h
)

for file in libelf/*.m4; do
    m4 -DSRCDIR=libelf "$file" > "${file%%.m4}.c"
done

make
make DESTDIR="$1" PREFIX=/usr install

# Install the license
install -Dm755 LICENSE "$1/usr/share/elftoolchain.license"
