#!/bin/sh -e

export DESTDIR="$1"

# mesa is shared
CFLAGS=$(printf %s "$CFLAGS" | sed 's/-static//g')

sed -i "s/gobject-2.0', v/gobject-2.0', static: true, v/" meson.build
sed -i "s/fontconfig', v/fontconfig', static: true, v/"   meson.build
sed -i "s/glib-2.0', v/glib-2.0', static: true, v/"       meson.build
sed -i "s/harfbuzz', v/harfbuzz', static: true, v/"       meson.build
sed -i "s/freetype', v/freetype', static: true, v/"       meson.build
sed -i "s/fribidi', v/fribidi', static: true, v/"         meson.build
sed -i "s/gio-2.0', v/gio-2.0', static: true, v/"         meson.build
sed -i "s/cairo', v/cairo', static: true, v/"             meson.build
sed -i "/subdir('examples')/d"                            meson.build
sed -i "/subdir('tests')/d"                               meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=static \
    -Dbuildtype=release \
    -Dgir=disabled \
    . build

ninja -C build
ninja -C build install
