#!/bin/sh -e

export DESTDIR="$1"

sed -i "/subdir('tests')/d"    meson.build
sed -i "/subdir('examples')/d" meson.build

meson \
    --prefix=/usr \
    --buildtype=release \
    -Dintrospection=disabled \
    -Dgir=disabled \
    . build

ninja -C build
ninja -C build install
