#!/bin/sh -e

LIBS="-lcurses -lterminfo" ./configure \
    --build=x86_64-linux-musl \
    --host=x86_64-linux-musl \
    --prefix=/usr \
    --disable-gtktest \
    --enable-nasm \
    --enable-shared \
    --enable-expopt=full

make
make DESTDIR="$1" install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/lame.license"
