#!/bin/sh -e

export DESTDIR="$1"

# Werror be damned.
sed -i 's/Werror/Wno-error/g' meson.build

meson \
    --prefix=/usr \
    -Ddefault_library=static \
    -Dbuildtype=release \
    -Dgtk_doc=false \
    -Dxft=disabled \
    -Dlibthai=disabled \
    -Dintrospection=disabled \
    --wrap-mode=nodownload \
    . build

ninja -C build
ninja -C build install

# Install the license
install -Dm755 COPYING "$1/usr/share/LICENSES/pango.license"
