#!/bin/sh -e

# When you're configure script doesn't respect cc
_cc="${CC:-$(readlink /usr/bin/cc)}"

./configure.py \
    --cc="$_cc" \
    --prefix=/usr \
    --without-documentation \
    --with-bzip \
    --with-lzma \
    --with-zlib

make
make DESTDIR="$1" install

# Install the license
install -Dm755 license.txt "$1/usr/share/LICENSES/botan.license"
