#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    -Dbuildtype=release \
    -Ddefault_library=both \
    -Dps=enabled \
    -Dtee=enabled \
    -Dtests=disabled \
    -Dtrace=disabled \
    -Dgl-backend=glesv2 \
    . build

ninja -C build
ninja -C build install
