#!/bin/sh -e

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

# Don't link with libatomic on LLVM systems
sed -i 's/-latomic//' node.gyp

CC=cc CXX=c++ ./configure \
    --prefix=/usr \
    --shared-zlib \
    --without-intl \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files
rm -rf \
    "$1/usr/include/node/openssl" \
    "$1/usr/share/doc" \
    "$1/usr/share/systemtap" \
    "$1/usr/lib/node_modules/npm/scripts" \
    "$1/usr/lib/node_modules/npm/configure"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/nodejs.license"
