#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_ENABLE_EH=ON \
    -DCLANG_BUILD_EXAMPLES=OFF \
    -DCLANG_INCLUDE_DOCS=OFF \
    -DCLANG_INCLUDE_TESTS=OFF \
    -DCLANG_DEFAULT_LINKER=lld \
    -DCLANG_DEFAULT_CXX_STDLIB=libc++ \
    -DCLANG_DEFAULT_RTLIB=compiler-rt \
    -DCLANG_DEFAULT_UNWINDLIB=libunwind \
    -DLIBCLANG_BUILD_STATIC=ON \
    -Wno-dev -G Ninja clang

cmake --build   build
cmake --install build

# Clang: Some legacy programs may require...
mkdir -p "$1/usr"
ln -s clang "$1/usr/bin/cc"
ln -s clang++ "$1/usr/bin/c++"
ln -s clang-cpp "$1/usr/bin/cpp"
install -m755 c99 "$1/usr/bin/c99"
