#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-bash-completion-dir=no \
    --with-fish-completion-dir=no \
    --with-zsh-completion-dir=no  \
    --enable-static

gmake
gmake DESTDIR="$1" install

ln -s ugrep "$1/usr/bin/grep"
ln -s ugrep "$1/usr/bin/fgrep"
ln -s ugrep "$1/usr/bin/egrep"
ln -s ugrep "$1/usr/bin/pgrep"

# Install the license
install -Dm644 LICENSE.txt "$1/usr/share/LICENSES/ugrep.license"
