#!/bin/sh -e

make headers

# rsync is required for headers_install.
# So we'll install them ourself. 

find usr/include -name \*.h -type f | while read -r file; do
    install -Dm644 "$file" "$1/$file" 
done
