#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < endianness.patch

sed -i 's/-Werror//' test/CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release

gmake -C build

mkdir -p "$1/usr/include" "$1/usr/lib/pkgconfig"
cp    -r glm              "$1/usr/include/glm"

cat >> "$1/usr/lib/pkgconfig/glm.pc" << EOF
prefix=/usr
includedir=${prefix}/include

Name: GLM
Description: OpenGL Mathematics
Version: 0.9.9
Cflags: -I${includedir}
EOF

# Install the license
install -Dm755 copying.txt "$1/usr/share/LICENSES/glm.license"
