#!/bin/sh -e

for opt in nspr nss; do
    make PREFIX=/usr -C "$opt" -f "makefile.$opt" 
    make PREFIX=/usr -C "$opt" -f "makefile.$opt" DESTDIR="$1" install
done

# Install the license
install -Dm755 nss/COPYING  "$1/usr/share/LICENSES/nss.license"
install -Dm755 nspr/LICENSE "$1/usr/share/LICENSES/nspr.license"
