#!/bin/sh -e
#shellcheck disable=1004,2086,2089,2090

log() {
    printf '%s\n' "---  $3  ---"
    printf '%s %s %s\n' $1 ${2##*/} ${3##*/}
}

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

DBI=$PWD/dist/build/include

CFLAGS="$CFLAGS -O2 -fPIC -m64 -pipe -ffunction-sections \
        -fdata-sections -pthread"

WARNINGS="-Wall -Wshadow -Qunused-arguments -Wno-parentheses-equality     \
          -Wno-array-bounds -Wno-unevaluated-expression -Wno-pointer-sign \
          -Wno-pointer-to-int-cast -Wno-implicit-function-declaration     \
          -Wno-parentheses -Wno-shadow -Wno-int-to-void-pointer-cast      \
          -Wno-macro-redefined"

CPPFLAGS="$CPPFLAGS -UDEBUG -DLINUX -Dlinux -DXP_UNIX -DNSS_NO_GCC48 \
          -DNDEBUG -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_SOURCE   \
          -DSDB_MEASURE_USE_TEMP_DIR -DNSS_NO_INIT_SUPPORT           \
          -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT -DHAVE_STRERROR   \
          -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES"

NSPRCPP="$CPPFLAGS -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\"      \
         -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\"              \
         -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DNDEBUG=1    \
         -DHAVE_VISIBILITY_HIDDEN_ATTRIBUTE=1 -D_PR_PTHREADS       \
         -DHAVE_VISIBILITY_PRAGMA=1 -DXP_UNIX=1 -D_GNU_SOURCE=1    \
         -DHAVE_FCNTL_FILE_LOCKING=1 -DHAVE_POINTER_LOCALTIME_R=1  \
         -DLINUX=1 -DHAVE_DLADDR=1 -DHAVE_GETTID=1 -DHAVE_LCHOWN=1 \
         -DHAVE_SETPRIORITY=1 -DHAVE_STRERROR=1 -DHAVE_SYSCALL=1   \
         -DHAVE_SECURE_GETENV=1 -D_REENTRANT=1 -DFORCE_PR_LOG      \
         -UHAVE_CVAR_BUILT_ON_SEM"

NSSCPP="-DNSS_SHLIB_VERSION=\"3\" -DSHLIB_PREFIX=\"lib\"     \
        -DSHLIB_SUFFIX=\"so\" -DSOFTOKEN_SHLIB_VERSION=\"3\" \
        -DMOZILLA_CLIENT=1 -DNSS_X64 -DNSS_X86_OR_X64"

INCLUDES="-I$DBI -I$DBI/public -I$DBI/private \
          -I$DBI/private/nss -I$DBI/public/nss"

FLAGS="$CFLAGS $WARNINGS $CPPFLAGS $INCLUDES"
NSPRFLAGS="-fvisibility=hidden $FLAGS $NSPRCPP"
NSSFLAGS="-std=c99 $FLAGS $NSSCPP"

### NSPR ###

npi=nspr/pr/include
for file in $npi/md/*.cfg $npi/private/*.h $npi/obsolete/*.h $npi/*.h; do
    case "$file" in
        *pprmwait.h) ;;
        $npi/md/*.cfg)     install -Dm444 -t $DBI/md       $file ;;
        $npi/private/*.h)  install -Dm444 -t $DBI/private  $file ;;
        $npi/obsolete/*.h) install -Dm444 -t $DBI/obsolete $file ;;
        *.h)               install -Dm444 -t $DBI          $file ;;
    esac
done

mv -f $npi/md/_linux.cfg $DBI/prcpucfg.h

nps="nspr/pr/src"
incs="-I$npi -I$npi/private"
sources="$nps/io/prfdcach.c $nps/io/priometh.c $nps/io/pripv6.c                \
         $nps/io/prlayer.c $nps/io/prlog.c $nps/io/prmapopt.c $nps/io/prmmap.c \
         $nps/io/prmwait.c $nps/io/prpolevt.c $nps/io/prprf.c                  \
         $nps/io/prscanf.c $nps/io/prstdio.c $nps/linking/prlink.c             \
         $nps/malloc/prmalloc.c $nps/malloc/prmem.c $nps/md/prosdep.c          \
         $nps/md/unix/linux.c $nps/md/unix/unix.c $nps/md/unix/unix_errors.c   \
         $nps/md/unix/uxproces.c $nps/md/unix/uxrng.c $nps/md/unix/uxshm.c     \
         $nps/md/unix/uxwrap.c $nps/memory/prseg.c $nps/memory/prshm.c         \
         $nps/memory/prshma.c $nps/misc/pralarm.c $nps/misc/pratom.c           \
         $nps/misc/praton.c $nps/misc/prcountr.c $nps/misc/prdtoa.c            \
         $nps/misc/prenv.c $nps/misc/prerr.c $nps/misc/prerror.c               \
         $nps/misc/prerrortable.c $nps/misc/prinit.c $nps/misc/prinrval.c      \
         $nps/misc/pripc.c $nps/misc/prlog2.c $nps/misc/prlong.c               \
         $nps/misc/prnetdb.c $nps/misc/prolock.c $nps/misc/prrng.c             \
         $nps/misc/prsystem.c $nps/misc/prthinfo.c $nps/misc/prtime.c          \
         $nps/misc/prtpool.c $nps/misc/prtrace.c $nps/pthreads/ptio.c          \
         $nps/pthreads/ptmisc.c $nps/pthreads/ptsynch.c $nps/threads/prcmon.c  \
         $nps/pthreads/ptthread.c $nps/threads/prrwlock.c $nps/threads/prtpd.c"

for file in $sources; do
    log CC "${file%%.c}.o" "$file"
    cc $NSPRFLAGS $incs -c -o "${file%%.c}.o" "$file"
done

cc $NSPRFLAGS $incs -c -o \
    $nps/md/unix/os_Linux_x86_64.o $nps/md/unix/os_Linux_x86_64.s

log AR libnspr4.a xxx.o
ar rcs libnspr4.a $nps/io/*.o $nps/linking/prlink.o $nps/malloc/*.o  \
                  $nps/md/prosdep.o $nps/md/unix/*.o $nps/memory/*.o \
                  $nps/misc/*.o $nps/pthreads/*.o $nps/threads/*.o

cat >> nspr/pr/src/_pr_bld.h << EOF
#define _BUILD_STRING "$(date "+%Y-%m-%d %H:%M:%S")"
#define _BUILD_TIME $(date +%s)000000LL
#define _PRODUCTION "libnspr4.so"
EOF

log CC prvrsion.o prvrsion.c
cc -o nspr/pr/src/prvrsion.o -c $NSPRFLAGS -Inspr/pr/include \
    -Inspr/pr/include/private nspr/pr/src/prvrsion.c

log CC libnspr4.so xxx.o
cc -shared -Wl,-soname -Wl,libnspr4.so -o libnspr4.so $nps/prvrsion.o     \
    $nps/io/prfdcach.o $nps/io/prmwait.o $nps/io/prmapopt.o               \
    $nps/io/priometh.o $nps/io/pripv6.o $nps/io/prlayer.o $nps/io/prlog.o \
    $nps/io/prmmap.o $nps/io/prpolevt.o $nps/io/prprf.o $nps/io/prscanf.o \
    $nps/io/prstdio.o $nps/threads/prcmon.o $nps/threads/prrwlock.o       \
    $nps/threads/prtpd.o $nps/linking/prlink.o $nps/malloc/prmalloc.o     \
    $nps/malloc/prmem.o $nps/md/prosdep.o $nps/memory/prshm.o             \
    $nps/memory/prshma.o $nps/memory/prseg.o $nps/misc/pralarm.o          \
    $nps/misc/pratom.o $nps/misc/prcountr.o $nps/misc/prdtoa.o            \
    $nps/misc/prenv.o $nps/misc/prerr.o $nps/misc/prerror.o               \
    $nps/misc/prerrortable.o $nps/misc/prinit.o $nps/misc/prinrval.o      \
    $nps/misc/pripc.o $nps/misc/prlog2.o $nps/misc/prlong.o               \
    $nps/misc/prnetdb.o $nps/misc/praton.o $nps/misc/prolock.o            \
    $nps/misc/prrng.o $nps/misc/prsystem.o $nps/misc/prthinfo.o           \
    $nps/misc/prtpool.o $nps/misc/prtrace.o $nps/misc/prtime.o            \
    $nps/pthreads/ptsynch.o $nps/pthreads/ptio.o $nps/pthreads/ptthread.o \
    $nps/pthreads/ptmisc.o $nps/md/unix/unix.o $nps/md/unix/unix_errors.o \
    $nps/md/unix/uxproces.o $nps/md/unix/uxrng.o $nps/md/unix/uxshm.o     \
    $nps/md/unix/uxwrap.o $nps/md/unix/linux.o                            \
    $nps/md/unix/os_Linux_x86_64.o -m64 -z noexecstack -lpthread -ldl -lrt

install -Dm444 -t dist/build/lib libnspr4.a libnspr4.so
install -Dm444 -t dist/build/bin libnspr4.so

log CC planera.o plarena.c
cc $NSPRFLAGS -I./nspr/pr/include -c -o \
    nspr/lib/ds/plarena.o nspr/lib/ds/plarena.c
log CC plhash.o plhash.c
cc $NSPRFLAGS -I./nspr/pr/include -c -o \
    nspr/lib/ds/plhash.o nspr/lib/ds/plhash.c
log AR libplds4.a xxx.o
ar rcs libplds4.a nspr/lib/ds/plarena.o nspr/lib/ds/plhash.o

cat >> nspr/lib/ds/_pl_bld.h << EOF
#define _BUILD_STRING "$(date "+%Y-%m-%d %H:%M:%S")"
#define _BUILD_TIME $(date +%s)000000LL
#define _PRODUCTION "libnspr4.so"
EOF

log CC plvrsion.o plvrsion.c
cc $NSPRFLAGS -Idist/build/lib/ds -I$npi -c -o \
    nspr/lib/ds/plvrsion.o nspr/lib/ds/plvrsion.c

rm -f nspr/lib/ds/_pl_bld.h

log CCLD libplds4.so xxx.o
cc -shared -Wl,-soname -Wl,libplds4.so -o libplds4.so \
    nspr/lib/ds/plvrsion.o nspr/lib/ds/plarena.o       \
    nspr/lib/ds/plhash.o -m64 -z noexecstack -Ldist/build/lib -lnspr4

install -Dm444 -t dist/build/lib     libplds4.a libplds4.so
install -Dm444 -t dist/build/bin     libplds4.so
install -Dm444 -t dist/build/include nspr/lib/ds/plhash.h             \
                                     nspr/lib/ds/plarena.h            \
                                     nspr/lib/ds/plarenas.h           \
                                     nspr/lib/libc/include/plstr.h    \
                                     nspr/lib/libc/include/plerror.h  \
                                     nspr/lib/libc/include/plgetopt.h \
                                     nspr/lib/libc/include/plbase64.h

cat >> nspr/lib/libc/src/_pl_bld.h << EOF
#define _BUILD_STRING "$(date "+%Y-%m-%d %H:%M:%S")"
#define _BUILD_TIME $(date +%s)000000LL
#define _PRODUCTION "libnspr4.so"
EOF

for file in nspr/lib/libc/src/*.c; do
    case $file in
        *plvrsion.c) ;;
        *) log CC ${file%%.c}.o $file
        cc $NSPRFLAGS -c -o ${file%%.c}.o $file ;;
    esac
done

log AR libplc4.a xxx.o
ar rcs libplc4.a nspr/lib/libc/src/*.o

log CC plvrsion.o plvrsion.c
cc $NSPRFLAGS -Inspr/lib/libc/src -c -o \
    nspr/lib/libc/src/plvrsion.o nspr/lib/libc/src/plvrsion.c

log CCLD libplc4.so xxx.o
cc -shared -Wl,-soname -Wl,libplc4.so -o libplc4.so \
    nspr/lib/libc/src/*.o -m64 -z noexecstack -L./dist/lib -lnspr4

install -Dm444 -t dist/build/lib libplc4.a libplc4.so
install -Dm444 -t dist/build/bin libplc4.so

log CC mygetval.o mygetval.c
cc $NSPRFLAGS -c -o nspr/pr/tests/dll/mygetval.o nspr/pr/tests/dll/mygetval.c
log CC mysetval.o mysetval.c
cc $NSPRFLAGS -c -o nspr/pr/tests/dll/mysetval.o nspr/pr/tests/dll/mysetval.c
log CCLD libmy.so xxx.o
cc -shared -Wl,-soname -Wl,libmy.so -o libmy.so \
    nspr/pr/tests/dll/*.o -m64 -z noexecstack

log CC abstract.o abstract.c
cc $NSPRFLAGS -I$npi -I$npi/private -c -o \
    nspr/pr/tests/abstract.o nspr/pr/tests/abstract.c
log CCLD abstract abstract.o
cc nspr/pr/tests/abstract.o -Xlinker -rpath dist/build/lib \
    -Ldist/build/lib -lplc4 -lnspr4 -lpthread -o abstract

### NSS ###

nl=nss/lib
frb=$nl/freebl
nix=$nl/libpkix/pkix
nki=$nl/libpkix/pkix_pl_nss/pki
nys=$nl/libpkix/pkix_pl_nss/system
nym=$nl/libpkix/pkix_pl_nss/module
for file in $nl/base/baset.h $nl/base/base.h $nl/certdb/genname.h              \
    $nl/certdb/xconst.h $nl/certdb/certxutl.h $nl/certdb/certi.h               \
    $nl/certhigh/ocspti.h $nl/certhigh/ocspi.h $nl/cryptohi/keyi.h             \
    $nl/dev/ckhelper.h $nl/dev/devm.h $nl/dev/devtm.h $nl/dev/devt.h           \
    $nl/dev/dev.h $nl/dev/nssdevt.h $nl/dev/nssdev.h                           \
    $nl/libpkix/include/pkix.h $nl/libpkix/include/pkix_crlsel.h               \
    $nl/libpkix/include/pkix_errorstrings.h $nl/libpkix/include/pkix_results.h \
    $nl/libpkix/include/pkixt.h $nl/libpkix/include/pkix_certsel.h             \
    $nl/libpkix/include/pkix_params.h $nl/libpkix/include/pkix_revchecker.h    \
    $nl/libpkix/include/pkix_certstore.h $nl/libpkix/include/pkix_pl_pki.h     \
    $nl/libpkix/include/pkix_sample_modules.h nss/cmd/lib/basicutil.h          \
    $nl/libpkix/include/pkix_checker.h $nl/libpkix/include/pkix_pl_system.h    \
    $nl/libpkix/include/pkix_util.h $nix/certsel/pkix_certselector.h           \
    $nix/certsel/pkix_comcertselparams.h $nix/crlsel/pkix_comcrlselparams.h    \
    $nix/crlsel/pkix_crlselector.h $nix/checker/pkix_basicconstraintschecker.h \
    $nix/checker/pkix_certchainchecker.h $nix/checker/pkix_crlchecker.h        \
    $nix/checker/pkix_ekuchecker.h $nix/checker/pkix_expirationchecker.h       \
    $nix/checker/pkix_namechainingchecker.h                                    \
    $nix/checker/pkix_nameconstraintschecker.h $nix/checker/pkix_ocspchecker.h \
    $nix/checker/pkix_policychecker.h $nix/checker/pkix_revocationmethod.h     \
    $nix/checker/pkix_revocationchecker.h $nix/checker/pkix_signaturechecker.h \
    $nix/checker/pkix_targetcertchecker.h $nix/params/pkix_procparams.h        \
    $nix/params/pkix_trustanchor.h $nix/params/pkix_valparams.h                \
    $nix/params/pkix_resourcelimits.h $nix/results/pkix_buildresult.h          \
    $nix/results/pkix_policynode.h $nix/results/pkix_valresult.h               \
    $nix/results/pkix_verifynode.h $nix/store/pkix_store.h                     \
    $nix/top/pkix_build.h $nix/top/pkix_lifecycle.h $nix/top/pkix_validate.h   \
    $nix/util/pkix_tools.h $nix/util/pkix_error.h $nix/util/pkix_logger.h      \
    $nix/util/pkix_list.h $nki/pkix_pl_basicconstraints.h $nki/pkix_pl_cert.h  \
    $nki/pkix_pl_certpolicyinfo.h $nki/pkix_pl_certpolicymap.h                 \
    $nki/pkix_pl_certpolicyqualifier.h $nki/pkix_pl_crl.h $nki/pkix_pl_crldp.h \
    $nki/pkix_pl_crlentry.h $nki/pkix_pl_date.h $nki/pkix_pl_generalname.h     \
    $nki/pkix_pl_infoaccess.h $nki/pkix_pl_nameconstraints.h                   \
    $nki/pkix_pl_ocsprequest.h $nki/pkix_pl_ocspresponse.h                     \
    $nki/pkix_pl_publickey.h $nki/pkix_pl_x500name.h $nki/pkix_pl_ocspcertid.h \
    $nys/pkix_pl_common.h $nys/pkix_pl_mem.h $nys/pkix_pl_object.h             \
    $nys/pkix_pl_string.h $nys/pkix_pl_primhash.h $nys/pkix_pl_bigint.h        \
    $nys/pkix_pl_mutex.h $nys/pkix_pl_bytearray.h $nys/pkix_pl_lifecycle.h     \
    $nys/pkix_pl_oid.h $nys/pkix_pl_hashtable.h $nys/pkix_pl_rwlock.h          \
    $nys/pkix_pl_monitorlock.h $nym/pkix_pl_aiamgr.h nss/cmd/lib/secutil.h     \
    $nym/pkix_pl_colcertstore.h $nym/pkix_pl_httpcertstore.h                   \
    $nym/pkix_pl_httpdefaultclient.h $nym/pkix_pl_ldapt.h                      \
    $nym/pkix_pl_ldapcertstore.h $nym/pkix_pl_ldapresponse.h                   \
    $nym/pkix_pl_ldaprequest.h $nym/pkix_pl_ldapdefaultclient.h                \
    $nym/pkix_pl_nsscontext.h $nym/pkix_pl_pk11certstore.h                     \
    $nym/pkix_pl_socket.h $nl/pk11wrap/secmodi.h $nl/pk11wrap/secmodti.h       \
    $nl/pk11wrap/dev3hack.h $nl/pki/pki.h $nl/pki/pkit.h $nl/pki/nsspkit.h     \
    $nl/pki/nsspki.h $nl/pki/pkistore.h $nl/pki/pki3hack.h $nl/pki/pkitm.h     \
    $nl/pki/pkim.h $nl/util/verref.h $nl/util/templates.c $nl/nss/nssrenam.h   \
    $nl/nss/nssoptions.h $nl/ckfw/ck.h $nl/ckfw/ckfw.h $nl/ckfw/ckfwm.h        \
    $nl/ckfw/ckfwtm.h $nl/ckfw/ckmd.h $nl/ckfw/ckt.h $nl/crmf/crmfi.h          \
    $nl/crmf/crmfit.h $nl/crmf/cmmfi.h $nl/crmf/cmmfit.h $nl/pkcs7/p7local.h   \
    $nl/smime/cmslocal.h $frb/cmac.h  $frb/alghmac.h $frb/blake2b.h            \
    $frb/blapi.h $frb/chacha20poly1305.h $frb/hmacct.h $frb/secmpi.h           \
    $frb/secrng.h $frb/ec.h $frb/ecl/ecl.h $frb/ecl/ecl-curve.h                \
    $frb/ecl/eclt.h $nl/softoken/pkcs11ni.h $nl/softoken/softoken.h            \
    $nl/softoken/softoknt.h $nl/softoken/softkver.h $nl/softoken/sdb.h         \
    $nl/softoken/sftkdbt.h $nl/softoken/lgglue.h nss/cmd/lib/pk11table.h; do
    install -Dm444 -t $DBI/private/nss $file
done

for file in $nl/base/nssbaset.h $nl/base/nssbase.h $nl/certdb/cert.h         \
            $nl/certdb/certt.h $nl/certdb/certdb.h $nl/certhigh/ocsp.h       \
            $nl/certhigh/ocspt.h $nl/cryptohi/cryptohi.h                     \
            $nl/cryptohi/cryptoht.h $nl/cryptohi/key.h $nl/cryptohi/keyhi.h  \
            $nl/cryptohi/keyt.h $nl/cryptohi/keythi.h $nl/cryptohi/sechash.h \
            $nl/pk11wrap/secmod.h $nl/pk11wrap/secmodt.h                     \
            $nl/pk11wrap/secpkcs5.h $nl/pk11wrap/pk11func.h                  \
            $nl/pk11wrap/pk11hpke.h $nl/pk11wrap/pk11pub.h                   \
            $nl/pk11wrap/pk11priv.h $nl/pk11wrap/pk11sdr.h                   \
            $nl/pk11wrap/pk11pqg.h $nl/util/base64.h $nl/util/ciferfam.h     \
            $nl/util/eccutil.h $nl/util/hasht.h $nl/util/nssb64.h            \
            $nl/util/nssb64t.h $nl/util/nsslocks.h $nl/util/nssilock.h       \
            $nl/util/nssilckt.h $nl/util/nssrwlk.h $nl/util/nssrwlkt.h       \
            $nl/util/nssutil.h $nl/util/pkcs11.h $nl/util/pkcs11f.h          \
            $nl/util/pkcs11p.h $nl/util/pkcs11t.h $nl/util/pkcs11n.h         \
            $nl/util/pkcs11u.h $nl/util/pkcs1sig.h $nl/util/portreg.h        \
            $nl/util/secasn1.h $nl/util/secasn1t.h $nl/util/seccomon.h       \
            $nl/util/secder.h $nl/util/secdert.h $nl/util/secdig.h           \
            $nl/util/secdigt.h $nl/util/secitem.h $nl/util/secoid.h          \
            $nl/util/secoidt.h $nl/util/secport.h $nl/util/secerr.h          \
            $nl/util/utilmodt.h $nl/util/utilrename.h $nl/util/utilpars.h    \
            $nl/util/utilparst.h $nl/util/pkcs11uri.h $nl/nss/nss.h          \
            $nl/ckfw/nssck.api $nl/ckfw/nssckepv.h $nl/ckfw/nssckft.h        \
            $nl/ckfw/nssckfw.h $nl/ckfw/nssckfwc.h $nl/ckfw/nssckfwt.h       \
            $nl/ckfw/nssckg.h $nl/ckfw/nssckmdt.h $nl/ckfw/nssckt.h          \
            $nl/ckfw/builtins/nssckbi.h $nl/crmf/crmf.h $nl/crmf/crmft.h     \
            $nl/crmf/cmmf.h $nl/crmf/cmmft.h $nl/jar/jar.h $nl/jar/jar-ds.h  \
            $nl/jar/jarfile.h $nl/pkcs12/pkcs12t.h $nl/pkcs12/pkcs12.h       \
            $nl/pkcs12/p12plcy.h $nl/pkcs12/p12.h $nl/pkcs12/p12t.h          \
            $nl/pkcs7/secmime.h $nl/pkcs7/secpkcs7.h $nl/pkcs7/pkcs7t.h      \
            $nl/smime/cms.h $nl/smime/cmst.h $nl/smime/smime.h               \
            $nl/smime/cmsreclist.h $nl/ssl/ssl.h $nl/ssl/sslt.h              \
            $nl/ssl/sslerr.h $nl/ssl/sslexp.h $nl/ssl/sslproto.h             \
            $nl/ssl/preenc.h $nl/freebl/blapit.h $nl/freebl/shsign.h         \
            $nl/freebl/ecl/ecl-exp.h $nl/freebl/nsslowhash.h                 \
            $nl/softoken/lowkeyi.h $nl/softoken/lowkeyti.h; do
    install -Dm444 -t $DBI/public/nss $file
done

install -Dm444 -t $DBI/private/dbm $nl/dbm/include/hsearch.h
install -Dm444 -t $DBI/private/dbm $nl/dbm/include/page.h
install -Dm444 -t $DBI/private/dbm $nl/dbm/include/extern.h
install -Dm444 -t $DBI/private/dbm $nl/dbm/include/queue.h
install -Dm444 -t $DBI/private/dbm $nl/dbm/include/hash.h
install -Dm444 -t $DBI/private/dbm $nl/dbm/include/search.h
install -Dm444 -t $DBI/public/dbm  $nl/dbm/include/mcom_db.h
install -Dm444 -t $DBI/public/dbm  $nl/dbm/include/ncompat.h
install -Dm444 -t $DBI/public/dbm  $nl/dbm/include/winfile.h

for file in $nl/base/*.c $nl/certdb/*.c $nl/certhigh/*.c $nl/cryptohi/*.c \
    $nl/dev/*.c $nl/libpkix/pkix/certsel/*.c $nl/libpkix/pkix/crlsel/*.c   \
    $nl/libpkix/pkix/checker/*.c $nl/libpkix/pkix/params/*.c               \
    $nl/libpkix/pkix/results/*.c $nl/libpkix/pkix/store/*.c $nl/pki/*.c    \
    $nl/libpkix/pkix/top/*.c $nl/libpkix/pkix/util/*.c $nl/util/*.c        \
    $nl/libpkix/pkix_pl_nss/pki/*.c $nl/libpkix/pkix_pl_nss/system/*.c     \
    $nl/pk11wrap/*.c $nl/libpkix/pkix_pl_nss/module/*.c; do
    case $file in
        *debug_module.c|*secplcy.c) ;;
        *) log CC ${file%%.c}.o $file
        cc $NSSFLAGS -c -o ${file%%.c}.o $file ;;
    esac
done

log AR libnssb.a xxx.o
ar rcs libnssb.a $nl/base/*.o
install -Dm664 -t dist/build/lib libnssb.a
log AR libcertdb.a xxx.o
ar rcs libcertdb.a $nl/certdb/*.o
install -Dm664 -t dist/build/lib libcertdb.a
log AR libcerthi.a xxx.o
ar rcs libcerthi.a $nl/certhigh/*.o
install -Dm664 -t dist/build/lib libcerthi.a
log AR libcryptohi.a xxx.o
ar rcs libcryptohi.a $nl/cryptohi/*.o
install -Dm664 -t dist/build/lib libcryptohi.a
log AR libnssdev.a xxx.o
ar rcs libnssdev.a $nl/dev/*.o
install -Dm664 -t dist/build/lib libnssdev.a
log AR libpkixcertsel.a xxx.o
ar rcs libpkixcertsel.a $nl/libpkix/pkix/certsel/*.o
install -Dm664 -t dist/build/lib libpkixcertsel.a
log AR libpkixcrlsel.a xxx.o
ar rcs libpkixcrlsel.a $nl/libpkix/pkix/crlsel/*.o
install -Dm664 -t dist/build/lib libpkixcrlsel.a
log AR libpkixchecker.a xxx.o
ar rcs libpkixchecker.a $nl/libpkix/pkix/checker/*.o
install -Dm664 -t dist/build/lib libpkixchecker.a
log AR libpkixparams.a xxx.o
ar rcs libpkixparams.a $nl/libpkix/pkix/params/*.o
install -Dm664 -t dist/build/lib libpkixparams.a
log AR libpkixresults.a xxx.o
ar rcs libpkixresults.a $nl/libpkix/pkix/results/*.o
install -Dm664 -t dist/build/lib libpkixresults.a
log AR libpkixstore.a xxx.o
ar rcs libpkixstore.a $nl/libpkix/pkix/store/*.o
install -Dm664 -t dist/build/lib libpkixstore.a
log AR libpkixtop.a xxx.o
ar rcs libpkixtop.a $nl/libpkix/pkix/top/*.o
install -Dm664 -t dist/build/lib libpkixtop.a
log AR libpkixutil.a xxx.o
ar rcs libpkixutil.a $nl/libpkix/pkix/util/*.o
install -Dm664 -t dist/build/lib libpkixutil.a
log AR libpkixpki.a xxx.o
ar rcs libpkixpki.a $nl/libpkix/pkix_pl_nss/pki/*.o
install -Dm664 -t dist/build/lib libpkixpki.a
log AR libpkixsystem.a xxx.o
ar rcs libpkixsystem.a $nl/libpkix/pkix_pl_nss/system/*.o
install -Dm664 -t dist/build/lib libpkixsystem.a
log AR libpkixmodule.a xxx.o
ar rcs libpkixmodule.a $nl/libpkix/pkix_pl_nss/module/*.o
install -Dm664 -t dist/build/lib libpkixmodule.a
log AR libpk11wrap.a xxx.o
ar rcs libpk11wrap.a $nl/pk11wrap/*.o
install -Dm664 -t dist/build/lib libpk11wrap.a
log AR libnsspki.a xxx.o
ar rcs libnsspki.a  $nl/pki/*.o
install -Dm664 -t dist/build/lib libnsspki.a
log AR libnssutil.a xxx.o
ar rcs libnssutil.a $nl/util/*.o
install -Dm664 -t dist/build/lib libnssutil.a

for file in $nl/util/nssutil.def $nl/nss/nss.def $nl/smime/smime.def  \
    $nl/ckfw/builtins/nssckbi.def $nl/ssl/ssl.def $frb/freebl_hash.def \
    $nl/sysinit/nsssysinit.def $frb/freebl_hash_vector.def; do
    grep -v ';-' $file | sed -e 's,;+,,'     \
                             -e 's; DATA ;;' \
                             -e 's,;;,,'     \
                             -e 's,;.*,;,' > \
                             ${file##*/}
done

mv -f freebl_hash.def        freebl.def
mv -f freebl_hash_vector.def freeblpriv.def

log CC libnssutil3.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname \
   -Wl,libnssutil3.so -Wl,--version-script,nssutil.def -o \
   libnssutil3.so $nl/util/*.o -L./dist/build/lib -lplc4 \
   -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libnssutil.a
install -Dm775 -t dist/build/lib libnssutil3.so

for file in $nl/nss/*.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS -c -o ${file%%.c}.o $file
done

log AR libnss.a xxx.o
ar rcs libnss.a $nl/nss/*.o
install -Dm664 -t dist/build/lib libnss.a

log CC libnss3.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname -Wl,libnss3.so     \
    -Wl,--version-script,nss.def -o libnss3.so $nl/nss/*.o $nl/certhigh/*.o  \
    $nl/cryptohi/*.o $nl/pk11wrap/*.o $nl/certdb/*.o $nl/pki/*.o $nl/dev/*.o \
    $nl/base/*.o $nl/libpkix/pkix/certsel/*.o $nl/libpkix/pkix/checker/*.o   \
    $nl/libpkix/pkix/params/*.o $nl/libpkix/pkix/results/*.o                 \
    $nl/libpkix/pkix/top/*.o $nl/libpkix/pkix/util/*.o                       \
    $nl/libpkix/pkix/crlsel/*.o $nl/libpkix/pkix/store/*.o                   \
    $nl/libpkix/pkix_pl_nss/pki/*.o $nl/libpkix/pkix_pl_nss/system/*.o       \
    $nl/libpkix/pkix_pl_nss/module/*.o -L./dist/build/lib -lnssutil3 -lplc4  \
    -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libnss.a
install -Dm775 -t dist/build/lib libnss3.so

perl $nl/ckfw/builtins/certdata.perl \
     $nl/ckfw/builtins/certdata.txt  \
     $nl/ckfw/builtins/certdata.c

for file in $nl/ckfw/*.c $nl/ckfw/builtins/*.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS -c -o ${file%%.c}.o $file
done

log AR libnssckfw.a xxx.o
ar rcs libnssckfw.a $nl/ckfw/*.o
install -Dm664 -t dist/build/lib libnssckfw.a

log CC libnssckbi.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname -Wl,libnssckbi.so \
   -Wl,--version-script,nssckbi.def -o libnssckbi.so $nl/ckfw/builtins/*.o \
   dist/build/lib/libnssckfw.a dist/build/lib/libnssb.a -L./dist/build/lib  \
   -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/lib libnssckbi.so

perl $nl/ckfw/builtins/certdata.perl                \
     $nl/ckfw/builtins/testlib/certdata-testlib.txt \
     $nl/ckfw/builtins/testlib/certdata-testlib.c

for file in $nl/ckfw/builtins/testlib/*.c; do
    case $file in
        *certdata-testlib.c) log CC ${file%%.c}.o $file
            cc $NSSFLAGS -I$nl/ckfw/builtins -c -o ${file%%.c}.o $file ;;
        *) log CC ${file%%.c}.o $file
            cc $NSSFLAGS -I$nl/ckfw/builtins -c -o ${file%%.c}.o $file ;;
    esac
done

log CC libnssckbi-testlib.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname      \
    -Wl,libnssckbi-testlib.so -o libnssckbi-testlib.so         \
    $nl/ckfw/builtins/testlib/*.o dist/build/lib/libnssckfw.a \
    dist/build/lib/libnssb.a -L./dist/build/lib -lplc4 -lplds4 \
    -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/lib libnssckbi-testlib.so
install -Dm775 -t dist/build/lib libnssckbi.so
install -Dm664 -t dist/build/lib libnssckfw.a

for file in $nl/crmf/*.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS -c -o ${file%%.c}.o $file
done

log AR libcrmf.a xxx.o
ar rcs libcrmf.a $nl/crmf/*.o
install -Dm664 -t dist/build/lib libcrmf.a

for file in $nl/jar/jar-ds.c $nl/jar/jar.c $nl/jar/jarfile.c \
            $nl/jar/jarint.c $nl/jar/jarsign.c $nl/jar/jarver.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS -c -o ${file%%.c}.o $file
done

log AR libjar.a xxx.o
ar rcs libjar.a $nl/jar/*.o
install -Dm664 -t dist/build/lib libjar.a

for file in $nl/pkcs12/p12creat.c $nl/pkcs12/p12d.c $nl/pkcs12/p12dec.c  \
            $nl/pkcs12/p12e.c $nl/pkcs12/p12local.c $nl/pkcs12/p12plcy.c \
            $nl/pkcs12/p12tmpl.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS -c -o ${file%%.c}.o $file
done

log AR libpkcs12.a xxx.o
ar rcs libpkcs12.a $nl/pkcs12/*.o
install -Dm664 -t dist/build/lib libpkcs12.a

for file in $nl/pkcs7/*.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS -c -o ${file%%.c}.o $file
done

log AR libpkcs7.a xxx.o
ar rcs libpkcs7.a $nl/pkcs7/*.o
install -Dm664 -t dist/build/lib libpkcs7.a

for file in $nl/smime/*.c; do
    case $file in
        *smimesym.c) ;;
        *) log CC ${file%%.c}.o $file
        cc $NSSFLAGS -c -o ${file%%.c}.o $file ;;
    esac
done

log AR libsmime.a xxx.o
ar rcs libsmime.a $nl/smime/*.o

cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname -Wl,libsmime3.so     \
    -Wl,--version-script,smime.def -o libsmime3.so $nl/smime/*.o $nl/pkcs7/*.o \
    $nl/pkcs12/*.o -lnss3 -Ldist/build/lib -lnssutil3 -lplc4 -lplds4 -lnspr4   \
    -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libsmime.a
install -Dm775 -t dist/build/lib libsmime3.so

for file in $nl/ssl/*.c; do
    case $file in
        *dhe-param.c|*os2_err.c|*win32err.c) ;;
        *) log CC ${file%%.c}.o $file
        cc $NSSFLAGS -c -o ${file%%.c}.o $file ;;
    esac
done

log AR libssl.a xxx.o
ar rcs libssl.a $nl/ssl/*.o

cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname -Wl,libssl3.so       \
    -Wl,--version-script,ssl.def -o libssl3.so $nl/ssl/*.o -L./dist/build/lib \
    -lnss3 -lnssutil3 -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libssl.a
install -Dm775 -t dist/build/lib libssl3.so

cc $NSSFLAGS -c -o $nl/sysinit/nsssysinit.o $nl/sysinit/nsssysinit.c
ar rcs libnsssysinit.a $nl/sysinit/nsssysinit.o

cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname         \
    -Wl,libnsssysinit.so -Wl,--version-script,nsssysinit.def -o   \
    libnsssysinit.so $nl/sysinit/nsssysinit.o -L./dist/build/lib \
    -lnssutil3  -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libnsssysinit.a
install -Dm775 -t dist/build/lib libnsssysinit.so

for file in $nl/dbm/src/*.c; do
    case $file in
        *memmove.c|*snprintf.c|*strerror.c) ;;
        *) log CC ${file%%.c}.o $file
        cc $NSSFLAGS -DSTDC_HEADERS -DHAVE_SNPRINTF -DMEMMOVE \
        -D__DBINTERFACE_PRIVATE -I$DBI/public/dbm -I$DBI/private/dbm \
        -c -o ${file%%.c}.o $file ;;
    esac
done

log AR libdbm.a xxx.o
ar rcs libdbm.a $nl/dbm/src/*.o

install -Dm664 -t dist/build/lib libdbm.a

FRCC="-std=c99 -O2 -fPIC  -m64 -pipe -ffunction-sections -fdata-sections"
FRCPP="-DHAVE_STRERROR -DLINUX -Dlinux -DNSS_NO_GCC48 -DXP_UNIX -UDEBUG       \
       -DNDEBUG -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_SOURCE -DNSS_X64     \
       -DSDB_MEASURE_USE_TEMP_DIR -DRIJNDAEL_INCLUDE_TABLES -DNSS_USE_64      \
       -DNSS_NO_INIT_SUPPORT -DUSE_UTIL_DIRECTLY -DNO_NSPR_10_SUPPORT         \
       -DSSL_DISABLE_DEPRECATED_CIPHER_SUITE_NAMES  -DFREEBL_NO_DEPEND        \
       -DFREEBL_LOWHASH -DNSS_X86_OR_X64 -DUSE_HW_SHA2 -DNSS_BEVAND_ARCFOUR   \
       -DMPI_AMD64 -DMP_ASSEMBLY_MULTIPLY -DNSS_USE_COMBA -DMP_API_COMPATIBLE \
       -DMP_IS_LITTLE_ENDIAN -DUSE_HW_AES -DINTEL_GCM -DHAVE_INT128_SUPPORT   \
       -D_REENTRANT -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\"              \
       -DSHLIB_VERSION=\"3\" -DSOFTOKEN_SHLIB_VERSION=\"3\""
FRWRN="-Wall -Wshadow -Qunused-arguments -Wno-parentheses-equality \
       -Wno-array-bounds -Wno-unevaluated-expression"
FRINC="-I$DBI -I$DBI/public/nss -I$DBI/private/nss -I$frb/mpi     \
       -I$frb/ecl -I$frb/verified -I$frb/verified/kremlin/include \
       -I$frb/verified/kremlin/kremlib/dist/minimal -I$frb/deprecated"

FREEBLFLAGS="$FRCC $FRCPP $FRWRN $FRINC"

log CC loader.o loader.c
cc $FREEBLFLAGS -c -o loader.o $frb/loader.c
log AR libfreebl.a loader.o
ar rcs libfreebl.a loader.o

mkdir obj

srcs="$frb/freeblver.c $frb/ldvector.c $frb/sysrand.c $frb/md2.c $frb/ec.c     \
      $frb/verified/Hacl_Chacha20Poly1305_128.c $frb/alghmac.c $frb/rawhash.c  \
      $frb/arcfour.c $frb/arcfive.c $frb/verified/Hacl_Chacha20_Vec256.c       \
      $frb/blake2b.c $frb/crypto_primitives.c $frb/des.c $frb/drbg.c           \
      $frb/verified/Hacl_Chacha20Poly1305_256.c $frb/aeskeywrap.c $frb/dh.c    \
      $frb/camellia.c $frb/ecdecode.c $frb/mpi/mplogic.c $frb/mpi/mpi.c        \
      $frb/mpi/mp_gf2m.c $frb/verified/Hacl_Poly1305_256.c $frb/sha512.c       \
      $frb/md5.c $frb/cmac.c $frb/cts.c $frb/chacha20poly1305.c $frb/hmacct.c  \
      $frb/ctr.c $frb/blinit.c $frb/gcm.c $frb/fipsfreebl.c $frb/rijndael.c    \
      $frb/rsa.c $frb/pqg.c $frb/dsa.c $frb/rsapkcs.c  $frb/ecl/ecp_jac.c      \
      $frb/tlsprfalg.c $frb/jpake.c $frb/stubs.c $frb/aes-x86.c $frb/ecl/ecl.c \
      $frb/ecl/ecp_mont.c $frb/ecl/ec_naf.c $frb/ecl/ecp_jm.c $frb/gcm-x86.c   \
      $frb/ecl/ecp_secp521r1.c $frb/ecl/curve25519_64.c $frb/ecl/ecl_gf.c      \
      $frb/nsslowhash.c $frb/mpi/mpprime.c $frb/mpi/mpmontg.c $frb/shvfy.c     \
      $frb/deprecated/alg2268.c $frb/ecl/ecl_mult.c $frb/mpi/mpi_amd64.c       \
      $frb/mpi/mp_comba.c  $frb/ecl/ecp_aff.c $frb/deprecated/seed.c           \
      $frb/ecl/ecp_256.c $frb/ecl/ecp_384.c $frb/ecl/ecp_521.c $frb/sha_fast.c \
      $frb/ecl/ecp_256_32.c $frb/ecl/ecp_secp384r1.c $frb/ecl/ecp_25519.c      \
      $frb/verified/Hacl_Poly1305_32.c $frb/verified/Hacl_Chacha20.c           \
      $frb/mpi/mpcpucache.c $frb/intel-aes.s $frb/intel-gcm-wrap.c             \
      $frb/verified/Hacl_Chacha20Poly1305_32.c $frb/sha256-x86.c               \
      $frb/intel-gcm.s $frb/verified/Hacl_Curve25519_51.c $frb/desblapi.c      \
      $frb/verified/Hacl_Poly1305_128.c $frb/verified/Hacl_Chacha20_Vec128.c   \
      $frb/arcfour-amd64-gas.s $frb/mpi/mpi_amd64_common.S"
 for file in $srcs; do
     filen=${file##*/}
    case $file in
        $frb/desblapi.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS -fno-strict-aliasing \
                -c -o obj/${filen%%.c}.o $file ;;
        $frb/gcm-x86.c|$frb/aes-x86.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS -maes -mpclmul \
                -c -o obj/${filen%%.c}.o $file ;;
        $frb/sha256-x86.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS -msha -mssse3 -msse4.1 \
                -c -o obj/${filen%%.c}.o $file ;;
        $frb/intel-gcm-wrap.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS -mssse3 \
                -c -o obj/${filen%%.c}.o $file ;;
        *Hacl_Chacha20_Vec128.c|*Hacl_Chacha20Poly1305_128.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS -mssse3 -msse4.1 -msse4.2 -mavx -maes \
                -c -o obj/${filen%%.c}.o $file ;;
        *Hacl_Chacha20_Vec256.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS-mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -maes \
                -c -o obj/${filen%%.c}.o $file ;;
        *Hacl_Chacha20Poly1305_256.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS-mssse3 -msse4.1 -msse4.2 -mavx2 -maes \
                -c -o obj/${filen%%.c}.o $file ;;
        *Hacl_Poly1305_128.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS-mssse3 -msse4.1 -msse4.2 -mavx -maes -mpclmul \
                -c -o obj/${filen%%.c}.o $file ;;
        *Hacl_Poly1305_256.c)
            log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS-mssse3 -msse4.1 -msse4.2 -mavx -mavx2 -maes \
                -mpclmul -c -o obj/${filen%%.c}.o $file ;;
        *.s) log CC ${file%%.s}.o $file
            cc $FREEBLFLAGS -fPIC -Wa,--noexecstack \
                -c -o obj/${filen%%.s}.o $file ;;
        *.S) log CC ${file%%.S}.o $file
            cc $FREEBLFLAGS -fPIC -Wa,--noexecstack \
                -c -o obj/${filen%%.S}.o $file ;;
        *)  log CC ${file%%.c}.o $file
            cc $FREEBLFLAGS -c -o obj/${filen%%.c}.o $file ;;
    esac
done

log CC libfreeblpriv3.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname \
-Wl,libfreeblpriv3.so -Wl,--version-script,freeblpriv.def \
-Wl,-Bsymbolic -o libfreeblpriv3.so obj/*.o -ldl -lc

install -Dm775 -t dist/build/lib libfreeblpriv3.so

cc $FREEBLFLAGS -c -o $nl/freebl/lowhash_vector.o $nl/freebl/lowhash_vector.c

log CC libfreebl3.so lowhash_vector.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname -Wl,libfreebl3.so \
    -Wl,--version-script,freebl.def -Wl,-Bsymbolic -o libfreebl3.so         \
    $nl/freebl/lowhash_vector.o -ldl -lc

install -Dm775 -t dist/build/lib libfreebl3.so
install -Dm664 -t dist/build/lib libfreebl.a

LEGINC="$CFLAGS $WARNINGS $CPPFLAGS -I./dist/build/include \
    -I./dist/build/include/private/nss -I./dist/build/include/public/nss \
    -I$DBI/public/dbm"
for file in $nl/softoken/legacydb/*.c; do
    log CC ${file%%.c}.o $file
    cc $FLAGS -I$DBI/public/dbm -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\" \
    -DLG_LIB_NAME=\"libnssdbm3.so\" -c -o ${file%%.c}.o $file
done

log AR libnssdbm.a xxx.o
ar rcs libnssdbm.a $nl/softoken/legacydb/*.o

grep -v ';-' $nl/softoken/legacydb/nssdbm.def | sed -e 's,;+,,'     \
                                                    -e 's; DATA ;;' \
                                                    -e 's,;;,,'     \
                                                    -e 's,;.*,;,' > \
                                                    nssdbm.def

log CCLD libnssdbm3.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname -Wl,libnssdbm3.so    \
    -Wl,--version-script,nssdbm.def -o libnssdbm3.so $nl/softoken/legacydb/*.o \
    dist/build/lib/libfreebl.a dist/build/lib/libdbm.a -Ldist/build/lib        \
    -lnssutil3 -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libnssdbm.a
install -Dm775 -t dist/build/lib libnssdbm3.so

for file in $nl/softoken/*.c; do
    log CC ${file%%.c}.o $file
    cc $NSSFLAGS $INCLUDES -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\" \
    -DSOFTOKEN_LIB_NAME=\"libsoftokn3.so\" -DSHLIB_VERSION=\"3\" -c -o \
    ${file%%.c}.o $file
done

log AR libsoftokn.a xxx.o
ar rcs libsoftokn.a $nl/softoken/*.o

grep -v ';-' $nl/softoken/softokn.def | sed -e 's,;+,,'     \
                                            -e 's; DATA ;;' \
                                            -e 's,;;,,'     \
                                            -e 's,;.*,;,' > \
                                            softokn.def

log CCLD libsoftokn3.so xxx.o
cc -shared -m64 -Wl,--gc-sections -Wl,-z,defs -Wl,-soname         \
    -Wl,libsoftokn3.so -Wl,--version-script,softokn.def           \
    -o libsoftokn3.so $nl/softoken/*.o dist/build/lib/libfreebl.a \
    -Ldist/build/lib -lsqlite3 -lnssutil3 -lplc4 -lplds4          \
    -lnspr4 -lpthread -ldl -lc

install -Dm664 -t dist/build/lib libsoftokn.a
install -Dm775 -t dist/build/lib libsoftokn3.so

for file in nss/cmd/lib/*.c; do
    case $file in
        *berparse.c) ;;
        *) log CC ${file%%.c}.o $file
        cc $NSSFLAGS -DNSS_USE_STATIC_LIBS -c -o ${file%%.c}.o $file ;;
    esac
done

log AR libsectool.a xxx.o
ar rcs libsectool.a nss/cmd/lib/*.o

install -Dm664 -t dist/build/lib libsectool.a

log CC blapitest.o blapitest.c
cc $NSSFLAGS -DNSS_USE_STATIC_LIBS -Inss/lib/softoken -IDBI/public/dbm -c -o \
    nss/cmd/bltest/blapitest.o nss/cmd/bltest/blapitest.c

log CCLD bltest blapitest.o
cc -o bltest $NSSFLAGS -DNSS_USE_STATIC_LIBS -Inss/lib/softoken            \
    -I$DBI/public/seccmd -I$DBI/public/dbm -I$DBI/public/softoken          \
    nss/cmd/bltest/blapitest.o -m64 -z noexecstack libsectool.a libsmime.a \
    libssl.a libnss.a dist/build/lib/libpkcs12.a dist/build/lib/libpkcs7.a \
    dist/build/lib/libcerthi.a dist/build/lib/libcryptohi.a                \
    dist/build/lib/libpk11wrap.a dist/build/lib/libsoftokn.a               \
    dist/build/lib/libcertdb.a dist/build/lib/libnsspki.a                  \
    dist/build/lib/libnssdev.a dist/build/lib/libnssb.a                    \
    dist/build/lib/libfreebl.a dist/build/lib/libdbm.a                     \
    dist/build/lib/libpkixtop.a dist/build/lib/libpkixutil.a               \
    dist/build/lib/libpkixsystem.a dist/build/lib/libpkixcrlsel.a          \
    dist/build/lib/libpkixmodule.a dist/build/lib/libpkixstore.a           \
    dist/build/lib/libpkixparams.a dist/build/lib/libpkixchecker.a         \
    dist/build/lib/libpkixpki.a dist/build/lib/libpkixtop.a                \
    dist/build/lib/libpkixresults.a dist/build/lib/libpkixcertsel.a        \
    dist/build/lib/libnss.a dist/build/lib/libpk11wrap.a                   \
    dist/build/lib/libcerthi.a -Ldist/build/lib -lsqlite3 -lnssutil3       \
    -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/bin bltest

log CC ecperf.o ecperf.c
cc $NSSFLAGS -DNSS_USE_STATIC_LIBS -I$nl/softoken -c -o \
    nss/cmd/ecperf/ecperf.o nss/cmd/ecperf/ecperf.c

log CCLD ecperf ecperf.o
cc -o ecperf $NSSFLAGS -DNSS_USE_STATIC_LIBS -I$nl/softoken                   \
    nss/cmd/ecperf/ecperf.o -m64 -z noexecstack dist/build/lib/libsectool.a   \
    dist/build/lib/libsmime.a dist/build/lib/libssl.a dist/build/lib/libnss.a \
    dist/build/lib/libpkcs12.a dist/build/lib/libpkcs7.a                      \
    dist/build/lib/libcerthi.a dist/build/lib/libcryptohi.a                   \
    dist/build/lib/libpk11wrap.a dist/build/lib/libsoftokn.a                  \
    dist/build/lib/libcertdb.a dist/build/lib/libnsspki.a                     \
    dist/build/lib/libnssdev.a dist/build/lib/libnssb.a                       \
    dist/build/lib/libfreebl.a dist/build/lib/libdbm.a                        \
    dist/build/lib/libpkixtop.a dist/build/lib/libpkixutil.a                  \
    dist/build/lib/libpkixsystem.a dist/build/lib/libpkixcrlsel.a             \
    dist/build/lib/libpkixmodule.a dist/build/lib/libpkixstore.a              \
    dist/build/lib/libpkixparams.a dist/build/lib/libpkixchecker.a            \
    dist/build/lib/libpkixpki.a dist/build/lib/libpkixtop.a                   \
    dist/build/lib/libpkixresults.a dist/build/lib/libpkixcertsel.a           \
    dist/build/lib/libnss.a dist/build/lib/libpk11wrap.a                      \
    dist/build/lib/libcerthi.a -Ldist/build/lib -lsqlite3 -lnssutil3 -lplc4   \
    -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/bin ecperf

log CC fbectest.o fbectest.c
cc $NSSFLAGS -DNSS_USE_STATIC_LIBS -I$nl/softoken -c -o \
    nss/cmd/fbectest/fbectest.o nss/cmd/fbectest/fbectest.c

log CCLD fbectest fbectest.o
cc -o fbectest $NSSFLAGS -DNSS_USE_STATIC_LIBS -I$nl/softoken       \
    nss/cmd/fbectest/fbectest.o -m64 -z noexecstack                 \
    dist/build/lib/libsectool.a dist/build/lib/libsmime.a           \
    dist/build/lib/libssl.a dist/build/lib/libnss.a                 \
    dist/build/lib/libpkcs12.a dist/build/lib/libpkcs7.a            \
    dist/build/lib/libcerthi.a dist/build/lib/libcryptohi.a         \
    dist/build/lib/libpk11wrap.a dist/build/lib/libsoftokn.a        \
    dist/build/lib/libcertdb.a dist/build/lib/libnsspki.a           \
    dist/build/lib/libnssdev.a dist/build/lib/libnssb.a             \
    dist/build/lib/libfreebl.a dist/build/lib/libdbm.a              \
    dist/build/lib/libpkixtop.a dist/build/lib/libpkixutil.a        \
    dist/build/lib/libpkixsystem.a dist/build/lib/libpkixcrlsel.a   \
    dist/build/lib/libpkixmodule.a dist/build/lib/libpkixstore.a    \
    dist/build/lib/libpkixparams.a dist/build/lib/libpkixchecker.a  \
    dist/build/lib/libpkixpki.a dist/build/lib/libpkixtop.a         \
    dist/build/lib/libpkixresults.a dist/build/lib/libpkixcertsel.a \
    dist/build/lib/libnss.a dist/build/lib/libpk11wrap.a            \
    dist/build/lib/libcerthi.a -Ldist/build/lib -lsqlite3           \
    -lnssutil3 -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc
install -Dm775 -t dist/build/bin fbectest

log CC fipstest.o fipstest.c
cc $FLAGS -DNSS_USE_STATIC_LIBS -c -o \
    nss/cmd/fipstest/fipstest.o nss/cmd/fipstest/fipstest.c

log CCLD fipstest fipstest.o
cc -o fipstest $FLAGS -DNSS_USE_STATIC_LIBS nss/cmd/fipstest/fipstest.o \
    -m64 -z noexecstack dist/build/lib/libsectool.a                     \
    dist/build/lib/libsmime.a dist/build/lib/libssl.a                   \
    dist/build/lib/libnss.a dist/build/lib/libpkcs12.a                  \
    dist/build/lib/libpkcs7.a dist/build/lib/libcerthi.a                \
    dist/build/lib/libcryptohi.a dist/build/lib/libpk11wrap.a           \
    dist/build/lib/libsoftokn.a dist/build/lib/libcertdb.a              \
    dist/build/lib/libnsspki.a dist/build/lib/libnssdev.a               \
    dist/build/lib/libnssb.a dist/build/lib/libfreebl.a                 \
    dist/build/lib/libdbm.a dist/build/lib/libpkixtop.a                 \
    dist/build/lib/libpkixutil.a dist/build/lib/libpkixsystem.a         \
    dist/build/lib/libpkixcrlsel.a dist/build/lib/libpkixmodule.a       \
    dist/build/lib/libpkixstore.a dist/build/lib/libpkixparams.a        \
    dist/build/lib/libpkixchecker.a dist/build/lib/libpkixpki.a         \
    dist/build/lib/libpkixtop.a dist/build/lib/libpkixresults.a         \
    dist/build/lib/libpkixcertsel.a dist/build/lib/libnss.a             \
    dist/build/lib/libpk11wrap.a dist/build/lib/libcerthi.a             \
    -Ldist/build/lib -lsqlite3 -lnssutil3 -lplc4 -lplds4 -lnspr4        \
    -lpthread -ldl -lc

install -Dm775 -t dist/build/bin fipstest

log CC lowhashtest.o lowhashtest.c
cc $FLAGS -DNSS_USE_STATIC_LIBS -I$fbr -I$DBI/public/dmb \
    -c -o nss/cmd/lowhashtest/lowhashtest.o nss/cmd/lowhashtest/lowhashtest.c

log CCLD lowhashtest lowhashtest.o
cc -o lowhashtest $CFLAGS $CPPFLAGS $WARNINGS -DNSS_USE_STATIC_LIBS -I$fbr     \
    -I$DBI/public/dbm nss/cmd/lowhashtest/lowhashtest.o -m64                   \
    -z noexecstack dist/build/lib/libsectool.a dist/build/lib/libsmime.a       \
    dist/build/lib/libssl.a dist/build/lib/libnss.a dist/build/lib/libpkcs12.a \
    dist/build/lib/libpkcs7.a dist/build/lib/libcerthi.a                       \
    dist/build/lib/libcryptohi.a dist/build/lib/libpk11wrap.a                  \
    dist/build/lib/libsoftokn.a dist/build/lib/libcertdb.a                     \
    dist/build/lib/libnsspki.a dist/build/lib/libnssdev.a                      \
    dist/build/lib/libnssb.a dist/build/lib/libfreebl.a                        \
    dist/build/lib/libdbm.a dist/build/lib/libpkixtop.a                        \
    dist/build/lib/libpkixutil.a dist/build/lib/libpkixsystem.a                \
    dist/build/lib/libpkixcrlsel.a dist/build/lib/libpkixmodule.a              \
    dist/build/lib/libpkixstore.a dist/build/lib/libpkixparams.a               \
    dist/build/lib/libpkixchecker.a dist/build/lib/libpkixpki.a                \
    dist/build/lib/libpkixtop.a dist/build/lib/libpkixresults.a                \
    dist/build/lib/libpkixcertsel.a dist/build/lib/libnss.a                    \
    dist/build/lib/libpk11wrap.a dist/build/lib/libcerthi.a                    \
    dist/build/lib/libsectool.a -Ldist/build/lib -lsqlite3 -lnssutil3          \
    -lplc4 -lplds4 -lnssutil3 -lfreebl3 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/bin lowhashtest

log CC mangle.o mangle.c
cc $FLAGS -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\" -c -o \
   nss/cmd/shlibsign/mangle/mangle.o nss/cmd/shlibsign/mangle/mangle.c

log CCLD mangle mangle.o
cc -o mangle $FLAGS -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\" \
    nss/cmd/shlibsign/mangle/mangle.o -m64 -z noexecstack        \
    -Ldist/build/lib -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/bin mangle

log CC shlibsign.o shlibsign.c
cc $FLAGS -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\" -c -o \
   nss/cmd/shlibsign/shlibsign.o nss/cmd/shlibsign/shlibsign.c

log CCLD shlibsign shlibsign.o
cc -o shlibsign $FLAGS -DSHLIB_SUFFIX=\"so\" -DSHLIB_PREFIX=\"lib\"    \
    nss/cmd/shlibsign/shlibsign.o -m64 -z noexecstack -Ldist/build/lib \
    -lplc4 -lplds4 -lnspr4 -lpthread -ldl -lc

install -Dm775 -t dist/build/bin shlibsign

sh ./nss/cmd/shlibsign/sign.sh ./dist/build \
    ./ Linux ./dist/build/lib ./dist/build/lib/libsoftokn3.so

./shlibsign -v -i ./dist/build/lib/libsoftokn3.so
sh ./nss/cmd/shlibsign/sign.sh ./dist/build \
    ./ Linux ./dist/build/lib ./dist/build/lib/libfreebl3.so

./shlibsign -v -i ./dist/build/lib/libfreebl3.so

sh ./nss/cmd/shlibsign/sign.sh ./dist/build \
    ./ Linux ./dist/build/lib ./dist/build/lib/libfreeblpriv3.so

./shlibsign -v -i ./dist/build/lib/libfreeblpriv3.so

sh ./nss/cmd/shlibsign/sign.sh ./dist/build \
    ./ Linux ./dist/build/lib ./dist/build/lib/libnssdbm3.so

./shlibsign -v -i ./dist/build/lib/libnssdbm3.so

install -Dt "$1/usr/include/nss" -m644 dist/build/include/public/nss/*.h
install -Dt "$1/usr/include/nss" -m644 dist/build/include/*.h
install -Dt "$1/usr/lib"               dist/build/lib/*.so
install -Dt "$1/usr/lib"         -m644 dist/build/lib/*.chk

# Yucky. This is needed by chromium.
install -Dt "$1/usr/include/nss/obsolete" \
    -m644 dist/build/include/obsolete/*.h

# Install the NSPR files. This is a joint package as I'd
# rather not juggle which version of NSPR works best with NSS.
install -Dt "$1/usr/include/nspr" -m644 nspr/pr/include/*.h
install -Dt "$1/usr/include/nspr" -m644 nspr/lib/*/*.h

for lib in *.so; do
    install -Dt "$1/usr/lib" "$lib"
done

# Install the pkgconfig files
install -Dm644 nss.pc  "$1/usr/lib/pkgconfig/nss.pc"
install -Dm644 nspr.pc "$1/usr/lib/pkgconfig/nspr.pc"

# Install the license
install -Dm755 nss/COPYING  "$1/usr/share/LICENSES/nss.license"
install -Dm755 nspr/LICENSE "$1/usr/share/LICENSES/nspr.license"
