#!/bin/sh -e

mv config .config
LDFLAGS="$LDFLAGS --static" gmake
gmake PREFIX="$1/usr/bin" install_flat

chmod +s "$1/usr/bin/toybox"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/toybox.license"
