#!/bin/sh -e

patch -p1 < POSIX.patch

gmake LDFLAGS="$LDFLAGS --static"
gmake PREFIX="$1/usr/bin" install_flat

chmod gu+s "$1/usr/bin/toybox"

# Install the license
install -Dm755 LICENSE "$1/usr/share/LICENSES/toybox.license"
