#!/bin/sh -e

export DESTDIR="$1"

CFLAGS=$(printf   %s "$CFLAGS"   | sed 's/-flto=thin//')
CXXFLAGS=$(printf %s "$CXXFLAGS" | sed 's/-flto=thin//')

sed -i 's/SANITIZER_COMMON TRUE/SANITIZER_COMMON FALSE/' \
    compiler-rt/cmake/config-ix.cmake

    #-DLLVM_PROFDATA_FILE=profdata.prof \
    #-DLLVM_ENABLE_LTO=FULL \
cmake -B build \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;compiler-rt;libunwind;libcxxabi;libcxx;lld" \
    -DLLVM_HOST_TRIPLE="$(clang -dumpmachine)" \
    -DLLVM_TARGETS_TO_BUILD="host;AMDGPU" \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DLLVM_BUILD_LLVM_DYLIB=ON \
    -DLLVM_LINK_LLVM_DYLIB=ON \
    -DLLVM_ENABLE_TERMINFO=OFF \
    -DLLVM_ENABLE_LIBXML2=OFF \
    -DLLVM_ENABLE_LIBEDIT=OFF \
    -DLLVM_ENABLE_LIBCXX=ON \
    -DLLVM_ENABLE_ZLIB=OFF \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_ENABLE_PIC=ON \
    -DLLVM_ENABLE_LLD=ON \
    -DLLVM_ENABLE_EH=ON \
    -DLLVM_INSTALL_BINUTILS_SYMLINKS=ON \
    -DCLANG_DEFAULT_CXX_STDLIB=libc++ \
    -DCLANG_DEFAULT_RTLIB=compiler-rt \
    -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON \
    -DLIBCXX_STATICALLY_LINK_ABI_IN_SHARED_LIBRARY=ON \
    -DLIBCXX_STATICALLY_LINK_ABI_IN_STATIC_LIBRARY=ON \
    -DLIBCXX_USE_COMPILER_RT=ON \
    -DLIBCXX_CXX_ABI=libcxxabi \
    -DLIBCXX_HAS_MUSL_LIBC=ON \
    -DLIBCXXABI_STATICALLY_LINK_UNWINDER_IN_SHARED_LIBRARY=ON \
    -DLIBCXXABI_ENABLE_STATIC_UNWINDER=ON \
    -DLIBCXXABI_USE_LLVM_UNWINDER=ON \
    -DLIBCXXABI_USE_COMPILER_RT=ON \
    -DLIBCXXABI_ENABLE_SHARED=OFF \
    -DLIBUNWIND_USE_COMPILER_RT=ON \
    -DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF \
    -DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON \
    -Wno-dev llvm -G Ninja

ninja -C build
ninja -C build install

# libc++abi header files
install -Dm644 libcxxabi/include/*.h "$1/usr/include"

# LLD: Replace GNU binutils
ln -s ld.lld "$1/usr/bin/ld"

# Clang: Some legacy programs may require cc/c++/cpp
ln -s clang     "$1/usr/bin/cc"
ln -s clang++   "$1/usr/bin/c++"
ln -s clang-cpp "$1/usr/bin/cpp"

# Clang: POSIX compliance
install -Dm755 c99 "$1/usr/bin/c99"

# Clang: Override libexec, the path is hardcoded, unfortunately.
mv -f "$1/usr/libexec/ccc-analyzer" "$1/usr/lib/clang"
mv -f "$1/usr/libexec/c++-analyzer" "$1/usr/lib/clang"

rm -r "$1/usr/libexec"

sed -i "s|libexec|lib/clang|" "$1/usr/bin/scan-build"

# Install the license
install -Dm755 llvm/LICENSE.TXT "$1/usr/share/LICENSES/llvm.license"
