#!/bin/sh -e 

mkdir -p node_modules/.bin

ln -sf /usr/bin/marked{,-man} node_modules/.bin/

sed -i 's|node bin/npm-cli.js install marked|true |' Makefile
sed -i 's/install: all/install:/' Makefile
mkdir -p man/man1


NODE_PATH=/usr/lib/node_modules make 

make NPMOTS="--prefix=\"$1/usr\"" install

chmod -R u=rwX,go=rX "$1"
chown -R root:root "$1"

_npmdir="$pkgdir"/usr/lib/node_modules/$1
rm -r "$_npmdir"/node_modules/{,.bin/}semver
rm -r "$_npmdir"/node_modules/{,.bin/}node-gyp

sed -i '/node-gyp.js/c\ exec /usr/bin/node-gyp "$@"' \
        "$_npmdir"/node_modules/npm-lifecycle/node-gyp-bin/node-gyp \ 
        "$_npmdir"/bin/node-gyp-bin/node-gyp

install -Dm755 "$1"/usr/share/bash-completions/completions
node "$1"/cli-6.13.7/bin/npm-cli.js completion > "$1"/usr/share/bash-completion/completions/npm

install -Dm644 "$1"/cli-6.13.7/LICENSE "$1"/usr/share/licenses/npm/LICENSE
